In [1]:
import numpy as np

In [2]:
mit_train = np.genfromtxt("mitbih_train.csv",delimiter=",")

In [3]:
mit_train_x_complete = mit_train[:,:-1]
mit_train_y_complete = mit_train[:,-1]

In [4]:
np.random.seed(6)
train_samp = np.random.choice(mit_train_x_complete.shape[0],replace=False,size=80000)
mit_train_x = mit_train_x_complete[train_samp]
mit_train_y = mit_train_y_complete[train_samp]
#mit_train_x = mit_train_x_complete[:]
#mit_train_y = mit_train_y_complete[:]

mit_val_x = mit_train_x_complete[np.setdiff1d(np.arange(mit_train_x_complete.shape[0]),train_samp)]
mit_val_y = mit_train_y_complete[np.setdiff1d(np.arange(mit_train_x_complete.shape[0]),train_samp)]

In [5]:
mit_test = np.genfromtxt("mitbih_test.csv",delimiter=",")

In [6]:
mit_test_x = mit_test[:,:-1]
mit_test_y = mit_test[:,-1]
mit_test_x.shape,mit_test_y.shape

((21892, 187), (21892,))

In [7]:
import linmdtw

In [8]:
linmdtw.dtw.__dir__()

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__file__',
 '__cached__',
 '__builtins__',
 'np',
 'get_diag_len',
 'get_diag_indices',
 'update_alignment_metadata',
 'warnings',
 'check_euclidean_inputs',
 'dtw_brute',
 'dtw_brute_backtrace',
 'dtw_diag',
 'linmdtw']

# confirm linmdtw has same results as pyts.metrics.dtw

In [10]:
linmdtw.dtw.linmdtw(mit_train_x_complete[0][:,np.newaxis],mit_test_x[0][:,np.newaxis])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning: Y is not 32-bit, so creating 32-bit version
  warnings.warn("Y is not 32-bit, so creating 32-bit version")


(4.231606483459473,
 array([[  0,   0],
        [  1,   0],
        [  2,   1],
        [  3,   2],
        [  4,   2],
        [  5,   2],
        [  6,   2],
        [  7,   3],
        [  7,   4],
        [  7,   5],
        [  8,   6],
        [  9,   7],
        [  9,   8],
        [ 10,   9],
        [ 10,  10],
        [ 10,  11],
        [ 10,  12],
        [ 10,  13],
        [ 10,  14],
        [ 10,  15],
        [ 10,  16],
        [ 10,  17],
        [ 11,  18],
        [ 12,  18],
        [ 13,  18],
        [ 14,  19],
        [ 15,  20],
        [ 16,  20],
        [ 17,  20],
        [ 18,  20],
        [ 19,  21],
        [ 20,  22],
        [ 21,  22],
        [ 22,  23],
        [ 23,  23],
        [ 24,  23],
        [ 25,  23],
        [ 26,  24],
        [ 27,  24],
        [ 28,  25],
        [ 29,  25],
        [ 30,  25],
        [ 31,  25],
        [ 32,  25],
        [ 33,  25],
        [ 34,  25],
        [ 35,  25],
        [ 36,  25],
        [ 37,  25],


In [30]:
linmdtw.dtw.linmdtw(mit_train_x_complete[0][np.newaxis,:],mit_test_x[0][np.newaxis,:])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:36: UserWarning: X (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("X {} has more columns than rows; did you mean to transpose?".format(X.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:38: UserWarning: Y (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("Y {} has more columns than rows; did you mean to transpose?".format(Y.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning:

(2.3397376537323, array([[0, 0]]))

In [13]:
linmdtw.dtw.dtw_brute(mit_train_x_complete[0][:,np.newaxis],mit_test_x[0][:,np.newaxis])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning: Y is not 32-bit, so creating 32-bit version
  warnings.warn("Y is not 32-bit, so creating 32-bit version")


{'cost': 4.231606483459473, 'P': <MemoryView of 'ndarray' at 0x7f59b8f08d40>}

In [19]:
linmdtw.dtw.dtw_brute(mit_train_x_complete[0][np.newaxis,:],mit_test_x[0][np.newaxis,:])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:36: UserWarning: X (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("X {} has more columns than rows; did you mean to transpose?".format(X.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:38: UserWarning: Y (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("Y {} has more columns than rows; did you mean to transpose?".format(Y.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning:

{'cost': 2.3397376537323, 'P': <MemoryView of 'ndarray' at 0x7f59b7ce4a00>}

In [25]:
linmdtw.dtw.dtw_brute(mit_train_x_complete[1][np.newaxis,:],mit_test_x[0][np.newaxis,:])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:36: UserWarning: X (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("X {} has more columns than rows; did you mean to transpose?".format(X.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:38: UserWarning: Y (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("Y {} has more columns than rows; did you mean to transpose?".format(Y.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning:

{'cost': 2.203913927078247, 'P': <MemoryView of 'ndarray' at 0x7f59b75b1040>}

In [8]:
import pyts
import pyts.metrics

In [11]:
pyts.metrics.dtw(mit_train_x_complete[0],mit_test_x[0])

0.530081371945681

In [17]:
help(pyts.metrics.dtw)

Help on function dtw in module pyts.metrics.dtw:

dtw(x=None, y=None, dist='square', method='classic', options=None, precomputed_cost=None, return_cost=False, return_accumulated=False, return_path=False)
    Dynamic Time Warping (DTW) distance between two samples.
    
    Parameters
    ----------
    x : array-like, shape = (n_timestamps_1,)
        First array. Ignored if ``dist == 'precomputed'``.
    
    y : array-like, shape = (n_timestamps_2,)
        Second array. Ignored if ``dist == 'precomputed'``.
    
    dist : 'square', 'absolute', 'precomputed' or callable (default = 'square')
        Distance used. If 'square', the squared difference is used.
        If 'absolute', the absolute difference is used. If callable,
        it must be a function with a numba.njit() decorator that takes
        as input two numbers (two arguments) and returns a number.
        If 'precomputed', ``precomputed_cost`` must be the cost matrix and
        ``method`` must be 'classic', 'sakoechiba

In [18]:
pyts.metrics.dtw(mit_train_x_complete[0],mit_test_x[0],method='classic')

0.530081371945681

In [20]:
pyts.metrics.dtw(mit_train_x_complete[0],mit_test_x[0],method='fast')

2.3397375036031702

In [22]:
pyts.metrics.dtw(mit_train_x_complete[0],mit_test_x[0],method='multiscale')

1.0121151397829196

In [24]:
pyts.metrics.dtw(mit_train_x_complete[0],mit_test_x[0],method='sakoechiba')

1.1750542860085806

In [27]:
pyts.metrics.dtw(mit_train_x_complete[1],mit_test_x[0],method='fast')

2.2039139604539515

In [29]:
np.random.seed(3)
train_samps = np.random.choice(mit_train_x_complete.shape[0],100)
test_samps = np.random.choice(mit_test_x.shape[0],100)
train_samps,test_samps

(array([71530, 67224, 77049, 59011, 48056, 25365, 11261, 84627, 43883,
        23545, 50857, 62583, 64934, 59872, 64093, 66983, 72078, 19960,
         3610, 61777, 68246, 51458,  8127, 78465, 69555, 66394, 24133,
        72552,  4718, 30305, 72093, 47611, 76295, 31736, 76971,  7713,
        22907, 46415, 20656, 72724, 15198,  5525, 33151, 54990, 65012,
        54812, 73591, 82944,  8896, 74002, 17780, 14271, 81573, 42749,
        16046, 67697, 76801,  8021, 30666, 81643, 40828, 19428, 61027,
        68315, 61328, 23039, 43920, 37874, 43282, 40779, 41824,  7391,
        20621, 83358, 79805, 31028, 43505, 29180, 17138, 34818, 22564,
        62298, 50920, 49836, 54218,  8374,  1520, 16868, 28251, 57841,
        12565, 21105, 83768, 40552, 74023,  6429, 67248, 23585, 75247,
        68028]),
 array([ 4363,  3284, 11146,  4464,  9936, 10316,  4932, 19756,  1019,
        15248, 21218,  9394,  6081,  3329, 16319,  7170,  8675,  9364,
         7190, 18908, 17387,  8839, 18873, 13793,  5035,  66

In [46]:
linmdtw_samp = np.zeros((len(train_samps),len(test_samps)))
#pydtw_samp = np.zeros((len(train_samps),len(test_samps)))
for indi,i in enumerate(train_samps):
    for indj,j in enumerate(test_samps):
        linmdtw_samp[indi,indj] = linmdtw.dtw.linmdtw(mit_train_x_complete[i][np.newaxis,:],mit_test_x[j][np.newaxis,:],do_gpu=True)[0]
        #pydtw_samp[indi,indj] = pyts.metrics.dtw(mit_train_x_complete[i],mit_test_x[j],method='fast')

In [35]:
linmdtw_samp

array([[2.18117332, 3.06781411, 3.13914061, ..., 2.30204272, 2.64248753,
        3.51410532],
       [2.3878293 , 2.54395723, 2.74726224, ..., 2.40650082, 2.63697433,
        3.2042613 ],
       [2.67057824, 3.1623683 , 3.66666842, ..., 2.85865355, 3.20576692,
        3.88316298],
       ...,
       [6.55811691, 6.16709089, 6.54595613, ..., 6.9038868 , 6.89747   ,
        5.44892406],
       [3.14503002, 3.08807349, 3.39950824, ..., 2.93678594, 3.18232846,
        3.93653941],
       [2.3197186 , 3.21867037, 3.05972505, ..., 2.12075424, 2.54642844,
        3.78503609]])

In [36]:
pydtw_samp

array([[2.18117332, 3.06781372, 3.13914037, ..., 2.30204257, 2.64248744,
        3.51410491],
       [2.38782929, 2.54395726, 2.7472621 , ..., 2.40650077, 2.63697428,
        3.20426134],
       [2.67057838, 3.16236838, 3.66666838, ..., 2.85865347, 3.20576675,
        3.88316248],
       ...,
       [6.55811687, 6.16709098, 6.54595622, ..., 6.90388644, 6.89746975,
        5.44892409],
       [3.14503014, 3.08807305, 3.39950809, ..., 2.93678613, 3.18232844,
        3.93653938],
       [2.31971906, 3.21867031, 3.05972498, ..., 2.1207544 , 2.54642873,
        3.78503659]])

In [43]:
np.allclose(linmdtw_samp,pydtw_samp)

True

In [41]:
linmdtw.dtw.linmdtw(mit_train_x_complete[0:2],mit_test_x[0:2],use_gpu=True)

TypeError: linmdtw() got an unexpected keyword argument 'use_gpu'

In [40]:
linmdtw.dtw.linmdtw(mit_train_x_complete[1:2],mit_test_x[1:2])

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:36: UserWarning: X (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("X {} has more columns than rows; did you mean to transpose?".format(X.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:38: UserWarning: Y (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("Y {} has more columns than rows; did you mean to transpose?".format(Y.shape))


(3.6151552200317383, array([[0, 0]]))

# calculate dtw between each time series in the train set with each time series in the test set

In [ ]:
for_dists = []
for i in range(mit_test_x.shape[0]):
    this_dist = []
    for j in range(mit_train_x_complete.shape[0]):
        d = linmdtw.dtw.linmdtw(mit_train_x_complete[j][np.newaxis,:],mit_test_x[i][np.newaxis,:],do_gpu=True)[0]
        #d = pyts.metrics.dtw(mit_train_x_complete[j],mit_test_x[i],method="fast")
        this_dist.append(d)
    print(i,"done")
    for_dists.append(this_dist)

/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:36: UserWarning: X (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("X {} has more columns than rows; did you mean to transpose?".format(X.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:38: UserWarning: Y (1, 187) has more columns than rows; did you mean to transpose?
  warnings.warn("Y {} has more columns than rows; did you mean to transpose?".format(Y.shape))
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:40: UserWarning: X is not 32-bit, so creating 32-bit version
  warnings.warn("X is not 32-bit, so creating 32-bit version")
/zfsauton2/home/jjlong/miniconda3/envs/tf-gpu/lib/python3.9/site-packages/linmdtw-0.1.7-py3.9-linux-x86_64.egg/linmdtw/dtw.py:46: UserWarning:

0 done
1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 done
66 done
67 done
68 done
69 done
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
102 done
103 done
104 done
105 done
106 done
107 done
108 done
109 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
120 done
121 done
122 done
123

962 done
963 done
964 done
965 done
966 done
967 done
968 done
969 done
970 done
971 done
972 done
973 done
974 done
975 done
976 done
977 done
978 done
979 done
980 done
981 done
982 done
983 done
984 done
985 done
986 done
987 done
988 done
989 done
990 done
991 done
992 done
993 done
994 done
995 done
996 done
997 done
998 done
999 done
1000 done
1001 done
1002 done
1003 done
1004 done
1005 done
1006 done
1007 done
1008 done
1009 done
1010 done
1011 done
1012 done
1013 done
1014 done
1015 done
1016 done
1017 done
1018 done
1019 done
1020 done
1021 done
1022 done
1023 done
1024 done
1025 done
1026 done
1027 done
1028 done
1029 done
1030 done
1031 done
1032 done
1033 done
1034 done
1035 done
1036 done
1037 done
1038 done
1039 done
1040 done
1041 done
1042 done
1043 done
1044 done
1045 done
1046 done
1047 done
1048 done
1049 done
1050 done
1051 done
1052 done
1053 done
1054 done
1055 done
1056 done
1057 done
1058 done
1059 done
1060 done
1061 done
1062 done
1063 done
1064 done
1065 don

1786 done
1787 done
1788 done
1789 done
1790 done
1791 done
1792 done
1793 done
1794 done
1795 done
1796 done
1797 done
1798 done
1799 done
1800 done
1801 done
1802 done
1803 done
1804 done
1805 done
1806 done
1807 done
1808 done
1809 done
1810 done
1811 done
1812 done
1813 done
1814 done
1815 done
1816 done
1817 done
1818 done
1819 done
1820 done
1821 done
1822 done
1823 done
1824 done
1825 done
1826 done
1827 done
1828 done
1829 done
1830 done
1831 done
1832 done
1833 done
1834 done
1835 done
1836 done
1837 done
1838 done
1839 done
1840 done
1841 done
1842 done
1843 done
1844 done
1845 done
1846 done
1847 done
1848 done
1849 done
1850 done
1851 done
1852 done
1853 done
1854 done
1855 done
1856 done
1857 done
1858 done
1859 done
1860 done
1861 done
1862 done
1863 done
1864 done
1865 done
1866 done
1867 done
1868 done
1869 done
1870 done
1871 done
1872 done
1873 done
1874 done
1875 done
1876 done
1877 done
1878 done
1879 done
1880 done
1881 done
1882 done
1883 done
1884 done
1885 done


2606 done
2607 done
2608 done
2609 done
2610 done
2611 done
2612 done
2613 done
2614 done
2615 done
2616 done
2617 done
2618 done
2619 done
2620 done
2621 done
2622 done
2623 done
2624 done
2625 done
2626 done
2627 done
2628 done
2629 done
2630 done
2631 done
2632 done
2633 done
2634 done
2635 done
2636 done
2637 done
2638 done
2639 done
2640 done
2641 done
2642 done
2643 done
2644 done
2645 done
2646 done
2647 done
2648 done
2649 done
2650 done
2651 done
2652 done
2653 done
2654 done
2655 done
2656 done
2657 done
2658 done
2659 done
2660 done
2661 done
2662 done
2663 done
2664 done
2665 done
2666 done
2667 done
2668 done
2669 done
2670 done
2671 done
2672 done
2673 done
2674 done
2675 done
2676 done
2677 done
2678 done
2679 done
2680 done
2681 done
2682 done
2683 done
2684 done
2685 done
2686 done
2687 done
2688 done
2689 done
2690 done
2691 done
2692 done
2693 done
2694 done
2695 done
2696 done
2697 done
2698 done
2699 done
2700 done
2701 done
2702 done
2703 done
2704 done
2705 done


3426 done
3427 done
3428 done
3429 done
3430 done
3431 done
3432 done
3433 done
3434 done
3435 done
3436 done
3437 done
3438 done
3439 done
3440 done
3441 done
3442 done
3443 done
3444 done
3445 done
3446 done
3447 done
3448 done
3449 done
3450 done
3451 done
3452 done
3453 done
3454 done
3455 done
3456 done
3457 done
3458 done
3459 done
3460 done
3461 done
3462 done
3463 done
3464 done
3465 done
3466 done
3467 done
3468 done
3469 done
3470 done
3471 done
3472 done
3473 done
3474 done
3475 done
3476 done
3477 done
3478 done
3479 done
3480 done
3481 done
3482 done
3483 done
3484 done
3485 done
3486 done
3487 done
3488 done
3489 done
3490 done
3491 done
3492 done
3493 done
3494 done
3495 done
3496 done
3497 done
3498 done
3499 done
3500 done
3501 done
3502 done
3503 done
3504 done
3505 done
3506 done
3507 done
3508 done
3509 done
3510 done
3511 done
3512 done
3513 done
3514 done
3515 done
3516 done
3517 done
3518 done
3519 done
3520 done
3521 done
3522 done
3523 done
3524 done
3525 done


IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



6160 done
6161 done
6162 done
6163 done
6164 done
6165 done
6166 done
6167 done
6168 done
6169 done
6170 done
6171 done
6172 done
6173 done
6174 done
6175 done
6176 done
6177 done
6178 done
6179 done
6180 done
6181 done
6182 done
6183 done
6184 done
6185 done
6186 done
6187 done
6188 done
6189 done
6190 done
6191 done
6192 done
6193 done
6194 done
6195 done
6196 done
6197 done
6198 done
6199 done
6200 done
6201 done
6202 done
6203 done
6204 done
6205 done
6206 done
6207 done
6208 done
6209 done
6210 done
6211 done
6212 done
6213 done
6214 done
6215 done
6216 done
6217 done
6218 done
6219 done
6220 done
6221 done
6222 done
6223 done
6224 done
6225 done
6226 done
6227 done
6228 done
6229 done
6230 done
6231 done
6232 done
6233 done
6234 done
6235 done
6236 done
6237 done
6238 done
6239 done
6240 done
6241 done
6242 done
6243 done
6244 done
6245 done
6246 done
6247 done
6248 done
6249 done
6250 done
6251 done
6252 done
6253 done
6254 done
6255 done
6256 done
6257 done
6258 done
6259 done


6980 done
6981 done
6982 done
6983 done
6984 done
6985 done
6986 done
6987 done
6988 done
6989 done
6990 done
6991 done
6992 done
6993 done
6994 done
6995 done
6996 done
6997 done
6998 done
6999 done
7000 done
7001 done
7002 done
7003 done
7004 done
7005 done
7006 done
7007 done
7008 done
7009 done
7010 done
7011 done
7012 done
7013 done
7014 done
7015 done
7016 done
7017 done
7018 done
7019 done
7020 done
7021 done
7022 done
7023 done
7024 done
7025 done
7026 done
7027 done
7028 done
7029 done
7030 done
7031 done
7032 done
7033 done
7034 done
7035 done
7036 done
7037 done
7038 done
7039 done
7040 done
7041 done
7042 done
7043 done
7044 done
7045 done
7046 done
7047 done
7048 done
7049 done
7050 done
7051 done
7052 done
7053 done
7054 done
7055 done
7056 done
7057 done
7058 done
7059 done
7060 done
7061 done
7062 done
7063 done
7064 done
7065 done
7066 done
7067 done
7068 done
7069 done
7070 done
7071 done
7072 done
7073 done
7074 done
7075 done
7076 done
7077 done
7078 done
7079 done


7800 done
7801 done
7802 done
7803 done
7804 done
7805 done
7806 done
7807 done
7808 done
7809 done
7810 done
7811 done
7812 done
7813 done
7814 done
7815 done
7816 done
7817 done
7818 done
7819 done
7820 done
7821 done
7822 done
7823 done
7824 done
7825 done
7826 done
7827 done
7828 done
7829 done
7830 done
7831 done
7832 done
7833 done
7834 done
7835 done
7836 done
7837 done
7838 done
7839 done
7840 done
7841 done
7842 done
7843 done
7844 done
7845 done
7846 done
7847 done
7848 done
7849 done
7850 done
7851 done
7852 done
7853 done
7854 done
7855 done
7856 done
7857 done
7858 done
7859 done
7860 done
7861 done
7862 done
7863 done
7864 done
7865 done
7866 done
7867 done
7868 done
7869 done
7870 done
7871 done
7872 done
7873 done
7874 done
7875 done
7876 done
7877 done
7878 done
7879 done
7880 done
7881 done
7882 done
7883 done
7884 done
7885 done
7886 done
7887 done
7888 done
7889 done
7890 done
7891 done
7892 done
7893 done
7894 done
7895 done
7896 done
7897 done
7898 done
7899 done


8620 done
8621 done
8622 done
8623 done
8624 done
8625 done
8626 done
8627 done
8628 done
8629 done
8630 done
8631 done
8632 done
8633 done
8634 done
8635 done
8636 done
8637 done
8638 done
8639 done
8640 done
8641 done
8642 done
8643 done
8644 done
8645 done
8646 done
8647 done
8648 done
8649 done
8650 done
8651 done
8652 done
8653 done
8654 done
8655 done
8656 done
8657 done
8658 done
8659 done
8660 done
8661 done
8662 done
8663 done
8664 done
8665 done
8666 done
8667 done
8668 done
8669 done
8670 done
8671 done
8672 done
8673 done
8674 done
8675 done
8676 done
8677 done
8678 done
8679 done
8680 done
8681 done
8682 done
8683 done
8684 done
8685 done
8686 done
8687 done
8688 done
8689 done
8690 done
8691 done
8692 done
8693 done
8694 done
8695 done
8696 done
8697 done
8698 done
8699 done
8700 done
8701 done
8702 done
8703 done
8704 done
8705 done
8706 done
8707 done
8708 done
8709 done
8710 done
8711 done
8712 done
8713 done
8714 done
8715 done
8716 done
8717 done
8718 done
8719 done


9440 done
9441 done
9442 done
9443 done
9444 done
9445 done
9446 done
9447 done
9448 done
9449 done
9450 done
9451 done
9452 done
9453 done
9454 done
9455 done
9456 done
9457 done
9458 done
9459 done
9460 done
9461 done
9462 done
9463 done
9464 done
9465 done
9466 done
9467 done
9468 done
9469 done
9470 done
9471 done
9472 done
9473 done
9474 done
9475 done
9476 done
9477 done
9478 done
9479 done
9480 done
9481 done
9482 done
9483 done
9484 done
9485 done
9486 done
9487 done
9488 done
9489 done
9490 done
9491 done
9492 done
9493 done
9494 done
9495 done
9496 done
9497 done
9498 done
9499 done
9500 done
9501 done
9502 done
9503 done
9504 done
9505 done
9506 done
9507 done
9508 done
9509 done
9510 done
9511 done
9512 done
9513 done
9514 done
9515 done
9516 done
9517 done
9518 done
9519 done
9520 done
9521 done
9522 done
9523 done
9524 done
9525 done
9526 done
9527 done
9528 done
9529 done
9530 done
9531 done
9532 done
9533 done
9534 done
9535 done
9536 done
9537 done
9538 done
9539 done


10236 done
10237 done
10238 done
10239 done
10240 done
10241 done
10242 done
10243 done
10244 done
10245 done
10246 done
10247 done
10248 done
10249 done
10250 done
10251 done
10252 done
10253 done
10254 done
10255 done
10256 done
10257 done
10258 done
10259 done
10260 done
10261 done
10262 done
10263 done
10264 done
10265 done
10266 done
10267 done
10268 done
10269 done
10270 done
10271 done
10272 done
10273 done
10274 done
10275 done
10276 done
10277 done
10278 done
10279 done
10280 done
10281 done
10282 done
10283 done
10284 done
10285 done
10286 done
10287 done
10288 done
10289 done
10290 done
10291 done
10292 done
10293 done
10294 done
10295 done
10296 done
10297 done
10298 done
10299 done
10300 done
10301 done
10302 done
10303 done
10304 done
10305 done
10306 done
10307 done
10308 done
10309 done
10310 done
10311 done
10312 done
10313 done
10314 done
10315 done
10316 done
10317 done
10318 done
10319 done
10320 done
10321 done
10322 done
10323 done
10324 done
10325 done
10326 done

10981 done
10982 done
10983 done
10984 done
10985 done
10986 done
10987 done
10988 done
10989 done
10990 done
10991 done
10992 done
10993 done
10994 done
10995 done
10996 done
10997 done
10998 done
10999 done
11000 done
11001 done
11002 done
11003 done
11004 done
11005 done
11006 done
11007 done
11008 done
11009 done
11010 done
11011 done
11012 done
11013 done
11014 done
11015 done
11016 done
11017 done
11018 done
11019 done
11020 done
11021 done
11022 done
11023 done
11024 done
11025 done
11026 done
11027 done
11028 done
11029 done
11030 done
11031 done
11032 done
11033 done
11034 done
11035 done
11036 done
11037 done
11038 done
11039 done
11040 done
11041 done
11042 done
11043 done
11044 done
11045 done
11046 done
11047 done
11048 done
11049 done
11050 done
11051 done
11052 done
11053 done
11054 done
11055 done
11056 done
11057 done
11058 done
11059 done
11060 done
11061 done
11062 done
11063 done
11064 done
11065 done
11066 done
11067 done
11068 done
11069 done
11070 done
11071 done

11726 done
11727 done
11728 done
11729 done
11730 done
11731 done
11732 done
11733 done
11734 done
11735 done
11736 done
11737 done
11738 done
11739 done
11740 done
11741 done
11742 done
11743 done
11744 done
11745 done
11746 done
11747 done
11748 done
11749 done
11750 done
11751 done
11752 done
11753 done
11754 done
11755 done
11756 done
11757 done
11758 done
11759 done
11760 done
11761 done
11762 done
11763 done
11764 done
11765 done
11766 done
11767 done
11768 done
11769 done
11770 done
11771 done
11772 done
11773 done
11774 done
11775 done
11776 done
11777 done
11778 done
11779 done
11780 done
11781 done
11782 done
11783 done
11784 done
11785 done
11786 done
11787 done
11788 done
11789 done
11790 done
11791 done
11792 done
11793 done
11794 done
11795 done
11796 done
11797 done
11798 done
11799 done
11800 done
11801 done
11802 done
11803 done
11804 done
11805 done
11806 done
11807 done
11808 done
11809 done
11810 done
11811 done
11812 done
11813 done
11814 done
11815 done
11816 done

12471 done
12472 done
12473 done
12474 done
12475 done
12476 done
12477 done
12478 done
12479 done
12480 done
12481 done
12482 done
12483 done
12484 done
12485 done
12486 done
12487 done
12488 done
12489 done
12490 done
12491 done
12492 done
12493 done
12494 done
12495 done
12496 done
12497 done
12498 done
12499 done
12500 done
12501 done
12502 done
12503 done
12504 done
12505 done
12506 done
12507 done
12508 done
12509 done
12510 done
12511 done
12512 done
12513 done
12514 done
12515 done
12516 done
12517 done
12518 done
12519 done
12520 done
12521 done
12522 done
12523 done
12524 done
12525 done
12526 done
12527 done
12528 done
12529 done
12530 done
12531 done
12532 done
12533 done
12534 done
12535 done
12536 done
12537 done
12538 done
12539 done
12540 done
12541 done
12542 done
12543 done
12544 done
12545 done
12546 done
12547 done
12548 done
12549 done
12550 done
12551 done
12552 done
12553 done
12554 done
12555 done
12556 done
12557 done
12558 done
12559 done
12560 done
12561 done

13216 done
13217 done
13218 done
13219 done
13220 done
13221 done
13222 done
13223 done
13224 done
13225 done
13226 done
13227 done
13228 done
13229 done
13230 done
13231 done
13232 done
13233 done
13234 done
13235 done
13236 done
13237 done
13238 done
13239 done
13240 done
13241 done
13242 done
13243 done
13244 done
13245 done
13246 done
13247 done
13248 done
13249 done
13250 done
13251 done
13252 done
13253 done
13254 done
13255 done
13256 done
13257 done
13258 done
13259 done
13260 done
13261 done
13262 done
13263 done
13264 done
13265 done
13266 done
13267 done
13268 done
13269 done
13270 done
13271 done
13272 done
13273 done
13274 done
13275 done
13276 done
13277 done
13278 done
13279 done
13280 done
13281 done
13282 done
13283 done
13284 done
13285 done
13286 done
13287 done
13288 done
13289 done
13290 done
13291 done
13292 done
13293 done
13294 done
13295 done
13296 done
13297 done
13298 done
13299 done
13300 done
13301 done
13302 done
13303 done
13304 done
13305 done
13306 done

13961 done
13962 done
13963 done
13964 done
13965 done
13966 done
13967 done
13968 done
13969 done
13970 done
13971 done
13972 done
13973 done
13974 done
13975 done
13976 done
13977 done
13978 done
13979 done
13980 done
13981 done
13982 done
13983 done
13984 done
13985 done
13986 done
13987 done
13988 done
13989 done
13990 done
13991 done
13992 done
13993 done
13994 done
13995 done
13996 done
13997 done
13998 done
13999 done
14000 done
14001 done
14002 done
14003 done
14004 done
14005 done
14006 done
14007 done
14008 done
14009 done
14010 done
14011 done
14012 done
14013 done
14014 done
14015 done
14016 done
14017 done
14018 done
14019 done
14020 done
14021 done
14022 done
14023 done
14024 done
14025 done
14026 done
14027 done
14028 done
14029 done
14030 done
14031 done
14032 done
14033 done
14034 done
14035 done
14036 done
14037 done
14038 done
14039 done
14040 done
14041 done
14042 done
14043 done
14044 done
14045 done
14046 done
14047 done
14048 done
14049 done
14050 done
14051 done

14706 done
14707 done
14708 done
14709 done
14710 done
14711 done
14712 done
14713 done
14714 done
14715 done
14716 done
14717 done
14718 done
14719 done
14720 done
14721 done
14722 done
14723 done
14724 done
14725 done
14726 done
14727 done
14728 done
14729 done
14730 done
14731 done
14732 done
14733 done
14734 done
14735 done
14736 done
14737 done
14738 done
14739 done
14740 done
14741 done
14742 done
14743 done
14744 done
14745 done
14746 done
14747 done
14748 done
14749 done
14750 done
14751 done
14752 done
14753 done
14754 done
14755 done
14756 done
14757 done
14758 done
14759 done
14760 done
14761 done
14762 done
14763 done
14764 done
14765 done
14766 done
14767 done
14768 done
14769 done
14770 done
14771 done
14772 done
14773 done
14774 done
14775 done
14776 done
14777 done
14778 done
14779 done
14780 done
14781 done
14782 done
14783 done
14784 done
14785 done
14786 done
14787 done
14788 done
14789 done
14790 done
14791 done
14792 done
14793 done
14794 done
14795 done
14796 done

15451 done
15452 done
15453 done
15454 done
15455 done
15456 done
15457 done
15458 done
15459 done
15460 done
15461 done
15462 done
15463 done
15464 done
15465 done
15466 done
15467 done
15468 done
15469 done
15470 done
15471 done
15472 done
15473 done
15474 done
15475 done
15476 done
15477 done
15478 done
15479 done
15480 done
15481 done
15482 done
15483 done
15484 done
15485 done
15486 done
15487 done
15488 done
15489 done
15490 done
15491 done
15492 done
15493 done
15494 done
15495 done
15496 done
15497 done
15498 done
15499 done
15500 done
15501 done
15502 done
15503 done
15504 done
15505 done
15506 done
15507 done
15508 done
15509 done
15510 done
15511 done
15512 done
15513 done
15514 done
15515 done
15516 done
15517 done
15518 done
15519 done
15520 done
15521 done
15522 done
15523 done
15524 done
15525 done
15526 done
15527 done
15528 done
15529 done
15530 done
15531 done
15532 done
15533 done
15534 done
15535 done
15536 done
15537 done
15538 done
15539 done
15540 done
15541 done

16196 done
16197 done
16198 done
16199 done
16200 done
16201 done
16202 done
16203 done
16204 done
16205 done
16206 done
16207 done
16208 done
16209 done
16210 done
16211 done
16212 done
16213 done
16214 done
16215 done
16216 done
16217 done
16218 done
16219 done
16220 done
16221 done
16222 done
16223 done
16224 done
16225 done
16226 done
16227 done
16228 done
16229 done
16230 done
16231 done
16232 done
16233 done
16234 done
16235 done
16236 done
16237 done
16238 done
16239 done
16240 done
16241 done
16242 done
16243 done
16244 done
16245 done
16246 done
16247 done
16248 done
16249 done
16250 done
16251 done
16252 done
16253 done
16254 done
16255 done
16256 done
16257 done
16258 done
16259 done
16260 done
16261 done
16262 done
16263 done
16264 done
16265 done
16266 done
16267 done
16268 done
16269 done
16270 done
16271 done
16272 done
16273 done
16274 done
16275 done
16276 done
16277 done
16278 done
16279 done
16280 done
16281 done
16282 done
16283 done
16284 done
16285 done
16286 done

16941 done
16942 done
16943 done
16944 done
16945 done
16946 done
16947 done
16948 done
16949 done
16950 done
16951 done
16952 done
16953 done
16954 done
16955 done
16956 done
16957 done
16958 done
16959 done
16960 done
16961 done
16962 done
16963 done
16964 done
16965 done
16966 done
16967 done
16968 done
16969 done
16970 done
16971 done
16972 done
16973 done
16974 done
16975 done
16976 done
16977 done
16978 done
16979 done
16980 done
16981 done
16982 done
16983 done
16984 done
16985 done
16986 done
16987 done
16988 done
16989 done
16990 done
16991 done
16992 done
16993 done
16994 done
16995 done
16996 done
16997 done
16998 done
16999 done
17000 done
17001 done
17002 done
17003 done
17004 done
17005 done
17006 done
17007 done
17008 done
17009 done
17010 done
17011 done
17012 done
17013 done
17014 done
17015 done
17016 done
17017 done
17018 done
17019 done
17020 done
17021 done
17022 done
17023 done
17024 done
17025 done
17026 done
17027 done
17028 done
17029 done
17030 done
17031 done

17686 done
17687 done
17688 done
17689 done
17690 done
17691 done
17692 done
17693 done
17694 done
17695 done
17696 done
17697 done
17698 done
17699 done
17700 done
17701 done
17702 done
17703 done
17704 done
17705 done
17706 done
17707 done
17708 done
17709 done
17710 done
17711 done
17712 done
17713 done
17714 done
17715 done
17716 done
17717 done
17718 done
17719 done
17720 done
17721 done
17722 done
17723 done
17724 done
17725 done
17726 done
17727 done
17728 done
17729 done
17730 done
17731 done
17732 done
17733 done
17734 done
17735 done
17736 done
17737 done
17738 done
17739 done
17740 done
17741 done
17742 done
17743 done
17744 done
17745 done
17746 done
17747 done
17748 done
17749 done
17750 done
17751 done
17752 done
17753 done
17754 done
17755 done
17756 done
17757 done
17758 done
17759 done
17760 done
17761 done
17762 done
17763 done
17764 done
17765 done
17766 done
17767 done
17768 done
17769 done
17770 done
17771 done
17772 done
17773 done
17774 done
17775 done
17776 done

18431 done
18432 done
18433 done
18434 done
18435 done
18436 done
18437 done
18438 done
18439 done
18440 done
18441 done
18442 done
18443 done
18444 done
18445 done
18446 done
18447 done
18448 done
18449 done
18450 done
18451 done
18452 done
18453 done
18454 done
18455 done
18456 done
18457 done
18458 done
18459 done
18460 done
18461 done
18462 done
18463 done
18464 done
18465 done
18466 done
18467 done
18468 done
18469 done
18470 done
18471 done
18472 done
18473 done
18474 done
18475 done
18476 done
18477 done
18478 done
18479 done
18480 done
18481 done
18482 done
18483 done
18484 done
18485 done
18486 done
18487 done
18488 done
18489 done
18490 done
18491 done
18492 done
18493 done
18494 done
18495 done
18496 done
18497 done
18498 done
18499 done
18500 done
18501 done
18502 done
18503 done
18504 done
18505 done
18506 done
18507 done
18508 done
18509 done
18510 done
18511 done
18512 done
18513 done
18514 done
18515 done
18516 done
18517 done
18518 done
18519 done
18520 done
18521 done

19176 done
19177 done
19178 done
19179 done
19180 done
19181 done
19182 done
19183 done
19184 done
19185 done
19186 done
19187 done
19188 done
19189 done
19190 done
19191 done
19192 done
19193 done
19194 done
19195 done
19196 done
19197 done
19198 done
19199 done
19200 done
19201 done
19202 done
19203 done
19204 done
19205 done
19206 done
19207 done
19208 done
19209 done
19210 done
19211 done
19212 done
19213 done
19214 done
19215 done
19216 done
19217 done
19218 done
19219 done
19220 done
19221 done
19222 done
19223 done
19224 done
19225 done
19226 done
19227 done
19228 done
19229 done
19230 done
19231 done
19232 done
19233 done
19234 done
19235 done
19236 done
19237 done
19238 done
19239 done
19240 done
19241 done
19242 done
19243 done
19244 done
19245 done
19246 done
19247 done
19248 done
19249 done
19250 done
19251 done
19252 done
19253 done
19254 done
19255 done
19256 done
19257 done
19258 done
19259 done
19260 done
19261 done
19262 done
19263 done
19264 done
19265 done
19266 done

19921 done
19922 done
19923 done
19924 done
19925 done
19926 done
19927 done
19928 done
19929 done
19930 done
19931 done
19932 done
19933 done
19934 done
19935 done
19936 done
19937 done
19938 done
19939 done
19940 done
19941 done
19942 done
19943 done
19944 done
19945 done
19946 done
19947 done
19948 done
19949 done
19950 done
19951 done
19952 done
19953 done
19954 done
19955 done
19956 done
19957 done
19958 done
19959 done
19960 done
19961 done
19962 done
19963 done
19964 done
19965 done
19966 done
19967 done
19968 done
19969 done
19970 done
19971 done
19972 done
19973 done
19974 done
19975 done
19976 done
19977 done
19978 done
19979 done
19980 done
19981 done
19982 done
19983 done
19984 done
19985 done
19986 done
19987 done
19988 done
19989 done
19990 done
19991 done
19992 done
19993 done
19994 done
19995 done
19996 done
19997 done
19998 done
19999 done
20000 done
20001 done
20002 done
20003 done
20004 done
20005 done
20006 done
20007 done
20008 done
20009 done
20010 done
20011 done

20666 done
20667 done
20668 done
20669 done
20670 done
20671 done
20672 done
20673 done
20674 done
20675 done
20676 done
20677 done
20678 done
20679 done
20680 done
20681 done
20682 done
20683 done
20684 done
20685 done
20686 done
20687 done
20688 done
20689 done
20690 done
20691 done
20692 done
20693 done
20694 done
20695 done
20696 done
20697 done
20698 done
20699 done
20700 done
20701 done
20702 done
20703 done
20704 done
20705 done
20706 done
20707 done
20708 done
20709 done
20710 done
20711 done
20712 done
20713 done
20714 done
20715 done
20716 done
20717 done
20718 done
20719 done
20720 done
20721 done
20722 done
20723 done
20724 done
20725 done
20726 done
20727 done
20728 done
20729 done
20730 done
20731 done
20732 done
20733 done
20734 done
20735 done
20736 done
20737 done
20738 done
20739 done
20740 done
20741 done
20742 done
20743 done
20744 done
20745 done
20746 done
20747 done
20748 done
20749 done
20750 done
20751 done
20752 done
20753 done
20754 done
20755 done
20756 done

21411 done
21412 done
21413 done
21414 done
21415 done
21416 done
21417 done
21418 done
21419 done
21420 done
21421 done
21422 done
21423 done
21424 done
21425 done
21426 done
21427 done
21428 done
21429 done
21430 done
21431 done
21432 done
21433 done
21434 done
21435 done
21436 done
21437 done
21438 done
21439 done
21440 done
21441 done
21442 done
21443 done
21444 done


In [10]:
test_dists_npy = np.array(for_dists)

In [11]:
test_dists_npy.shape

(21892, 87554)

In [12]:
import os
os.path.exists("test_linmdtw_full.npy")

False

In [13]:
np.save("test_linmdtw_full.npy",test_dists_npy)

In [59]:
test_dists_npy

array([[2.33973765, 2.20391393, 1.84586501, ..., 5.20528269, 3.67375565,
        4.77153158],
       [2.69668078, 3.61515522, 2.85678124, ..., 3.08926105, 4.09972143,
        4.25093365],
       [2.37009478, 2.75195909, 2.3533361 , ..., 4.43422222, 3.26398754,
        4.66661549],
       ...,
       [2.15213442, 2.32896733, 2.24866676, ..., 5.2135334 , 2.87344646,
        4.77909327],
       [2.95980954, 3.12669635, 3.19516397, ..., 4.43355417, 2.4108243 ,
        4.20903635],
       [4.19968557, 4.5585618 , 4.58236742, ..., 4.10391378, 2.72595644,
        3.96858835]])

# confirm again that dtw calculations agree

In [63]:
#linmdtw_samp = np.zeros((len(train_samps),len(test_samps)))
#pydtw_samp = np.zeros((len(train_samps),len(test_samps)))
for indi,i in enumerate(train_samps):
    for indj,j in enumerate(test_samps):
        #linmdtw_samp[indi,indj] = linmdtw.dtw.linmdtw(mit_train_x_complete[i][np.newaxis,:],mit_test_x[j][np.newaxis,:],do_gpu=True)[0]
        #pydtw_samp[indi,indj] = pyts.metrics.dtw(mit_train_x_complete[i],mit_test_x[j],method='fast')
        print(i,j, loaded_softdtw[j,i],pyts.metrics.dtw(mit_train_x_complete[i],mit_test_x[j],method='fast'),pyts.metrics.dtw(mit_test_x[j],mit_train_x_complete[i],method='fast'))

71530 4363 0.8977901938271438 2.181173317320707 2.181173317320707
71530 3284 1.7034316278464128 3.0678137217079335 3.0678137217079335
71530 11146 1.4234830453506397 3.139140373060818 3.139140373060818
71530 4464 1.2606771843035534 2.411456050196962 2.411456050196962
71530 9936 0.8769891232512584 2.1962042866838822 2.1962042866838822
71530 10316 0.9438421497402931 2.709870988539975 2.709870988539975
71530 4932 2.1608263354856763 3.051958180837198 3.051958180837198
71530 19756 0.4250924278829288 2.2130723405024684 2.2130723405024684
71530 1019 0.27627723612151855 2.2643916386164498 2.2643916386164498
71530 15248 0.9480557886683677 2.324085350301571 2.324085350301571
71530 21218 3.208693418874204 4.6882070991452505 4.6882070991452505
71530 9394 1.5421485480624366 3.2976054579675047 3.2976054579675047
71530 6081 1.9326717512488407 3.1431648927162663 3.1431648927162663
71530 3329 2.2486782352448205 2.8303805446143953 2.8303805446143953
71530 16319 0.24089454519771286 2.2240330900952485 2.22

67224 18873 1.2287754016610077 3.738677394945276 3.738677394945276
67224 13793 1.80279715423502 2.9163260613522533 2.9163260613522533
67224 5035 1.3085624836060705 2.8109663576030393 2.8109663576030393
67224 6688 1.521470200423356 2.890215725452192 2.890215725452192
67224 9820 0.6665004978855223 2.9684792437235603 2.9684792437235603
67224 14224 2.010328824384423 2.9832727877814658 2.9832727877814658
67224 4891 0.5515245246939601 2.7910506625271014 2.7910506625271014
67224 363 2.127800248417951 3.539904100611965 3.539904100611965
67224 4884 0.8384266320130039 2.7218502545021135 2.7218502545021135
67224 13064 0.756428964927096 3.4603732391343405 3.4603732391343405
67224 5784 0.6052328778979539 2.8986255040591473 2.8986255040591473
67224 13262 1.349692623660156 2.7921461541629595 2.7921461541629595
67224 7756 0.9164643149120658 3.0832384965960578 3.0832384965960578
67224 19987 0.97099116444923 3.845409926098415 3.845409926098415
67224 18532 1.282856808777009 3.2678932631313864 3.267893263

77049 7309 0.35782858053043587 2.6455297157728905 2.6455297157728905
77049 1534 0.5837789317437646 2.966696743926064 2.966696743926064
77049 5703 0.7241497980310331 2.5534014167424086 2.5534014167424086
77049 17244 0.2549195922182905 2.575044844114798 2.575044844114798
77049 13604 0.5812539066390028 2.5114804099906554 2.5114804099906554
77049 2248 0.6051101942828104 2.7600541838218104 2.7600541838218104
77049 20988 0.5223041999929968 2.4968025934573888 2.4968025934573888
77049 19482 2.859792734247992 4.530386850302205 4.530386850302205
77049 15508 0.7895004183953445 2.388255717109221 2.388255717109221
77049 3742 0.4691789928525817 2.669698133933056 2.669698133933056
77049 8849 0.3585830967106002 2.8410430325403992 2.8410430325403992
77049 16756 0.5890391457211607 2.7532289336278577 2.7532289336278577
77049 12320 0.4391386762890341 1.702469164875589 1.702469164875589
77049 10791 0.4400327253023281 2.811352719483615 2.811352719483615
77049 20319 1.5975871135934667 4.812726527397923 4.812

59011 12305 0.1331652081732622 2.7860400226532174 2.7860400226532174
59011 8627 0.1500466010517706 1.1555069479326971 1.1555069479326971
59011 6157 0.07626407536487056 2.1100635503946954 2.1100635503946954
59011 21087 1.2939127068468566 4.914805990890554 4.914805990890554
59011 13252 1.4097817679015012 3.385691415962692 3.385691415962692
59011 1023 0.23963791566401912 2.5374798195058283 2.5374798195058283
59011 6207 5.399093335449397 7.954704239398075 7.954704239398075
59011 4045 1.0192195694493007 3.60404108292498 3.60404108292498
59011 18016 0.15095132477505932 2.0660420751656 2.0660420751656
59011 17112 0.2671018376643927 2.9302130665718567 2.9302130665718567
59011 13372 1.819863870299744 3.470736940883555 3.470736940883555
59011 8111 1.0603039394304885 2.7430556636552046 2.7430556636552046
59011 19127 0.3990928714502593 3.4344172848247183 3.4344172848247183
59011 2282 0.31834764533170723 2.2169866271195673 2.2169866271195673
59011 19799 0.2786857537238205 2.300201483519881 2.300201

48056 7641 1.7914867482665182 3.3557276453369576 3.3557276453369576
48056 15035 1.0534589189867072 4.8619071102734885 4.8619071102734885
48056 4996 1.5599259441535447 3.2282086018964944 3.2282086018964944
48056 20053 0.7280193535106304 4.05422369222934 4.05422369222934
48056 8120 0.7862124872494445 2.1392915988423105 2.1392915988423105
48056 18093 0.9637216858000929 2.366910362437392 2.366910362437392
48056 19399 2.2077944533983187 3.1775956632635616 3.1775956632635616
25365 4363 0.41666538049116764 2.49772915042128 2.49772915042128
25365 3284 0.47778318127902625 1.938321128388198 1.938321128388198
25365 11146 0.8845941432441722 3.188817997732203 3.188817997732203
25365 4464 0.21366298386734645 2.7795182243889727 2.7795182243889727
25365 9936 0.8301969429296903 2.97923064407005 2.97923064407005
25365 10316 0.34629312363369064 2.784556764397115 2.784556764397115
25365 4932 1.252140744671726 3.088052033972033 3.088052033972033
25365 19756 0.2501128856991749 2.62391690727286 2.62391690727

11261 7190 3.402010639066159 3.4720779544675704 3.4720779544675704
11261 18908 2.2665680067924283 3.4208692017262154 3.4208692017262154
11261 17387 1.0584462790632734 2.2165377531461896 2.2165377531461896
11261 8839 1.337564318466736 3.2166371466964283 3.2166371466964283
11261 18873 2.0577547819313065 4.222043731848086 4.222043731848086
11261 13793 3.7241253846693505 3.8585283787345963 3.8585283787345963
11261 5035 3.614856020771086 3.263536047380785 3.263536047380785
11261 6688 3.964794903336778 3.872123021774481 3.872123021774481
11261 9820 1.7152080456912195 3.3173937176726973 3.3173937176726973
11261 14224 4.4070430579791715 3.4122596110506977 3.4122596110506977
11261 4891 1.3330738788860803 3.292767463800632 3.292767463800632
11261 363 2.2904681292364124 4.280985133455862 4.280985133455862
11261 4884 0.5868937565542016 1.5801836336803479 1.5801836336803479
11261 13064 0.9677573781152677 3.6973458878677286 3.6973458878677286
11261 5784 1.853231453191817 3.5216191359109184 3.5216191

84627 9834 2.68413317700942 4.12006174459945 4.12006174459945
84627 15697 2.113384217221829 2.8997644582983133 2.8997644582983133
84627 18976 4.414332323017821 3.4054038887798885 3.4054038887798885
84627 7309 1.9307543109841363 3.185458240505418 3.185458240505418
84627 1534 2.276445390332196 4.378206008812231 4.378206008812231
84627 5703 1.6171440868084286 3.837196725682429 3.837196725682429
84627 17244 1.4754998123282117 4.0563321458591775 4.0563321458591775
84627 13604 2.4236070460938346 4.684102321377254 4.684102321377254
84627 2248 2.442068572996163 4.580340899468835 4.580340899468835
84627 20988 1.8548267014410766 2.8707564058456008 2.8707564058456008
84627 19482 3.2419043977509294 3.613901955370989 3.613901955370989
84627 15508 2.3515593873327103 3.145345073377418 3.145345073377418
84627 3742 1.549213229082695 3.8317522008229035 3.8317522008229035
84627 8849 3.199180173279429 4.756013211973131 4.756013211973131
84627 16756 3.230346452754764 4.380576222842923 4.380576222842923
846

43883 18166 0.3124270345021505 2.1384049000871563 2.1384049000871563
43883 12305 0.4628835585126137 2.9236419237508753 2.9236419237508753
43883 8627 1.2133217714055184 3.0914890601293146 3.0914890601293146
43883 6157 0.5604599936192074 2.8882272414828525 2.8882272414828525
43883 21087 1.7466343797595956 3.747518376965117 3.747518376965117
43883 13252 0.5269135893355226 2.7509190441278744 2.7509190441278744
43883 1023 0.9662554915960317 3.1029023812704146 3.1029023812704146
43883 6207 4.18637637589337 6.624448383404019 6.624448383404019
43883 4045 1.4795231903547328 3.1758520871034377 3.1758520871034377
43883 18016 0.9748418224215474 3.374039688066588 3.374039688066588
43883 17112 1.7762279923389523 3.653191916044436 3.653191916044436
43883 13372 0.6863958388043088 2.525820629144387 2.525820629144387
43883 8111 0.9249597721053706 2.3615938203529576 2.3615938203529576
43883 19127 0.9767559696612207 3.6141107647320374 3.6141107647320374
43883 2282 0.3441927846393595 2.7853675504009767 2.7

23545 7641 1.234769725724697 2.5128148249500604 2.5128148249500604
23545 15035 3.3783312037524684 5.266011449572766 5.266011449572766
23545 4996 0.5198252341983769 2.479959394227904 2.479959394227904
23545 20053 0.5186199684070855 3.4484394733834005 3.4484394733834005
23545 8120 1.044357574834401 1.7946846586523415 1.7946846586523415
23545 18093 0.8686944143611313 2.21373215658189 2.21373215658189
23545 19399 2.3846170288806325 3.5222331085556626 3.5222331085556626
50857 4363 3.8345515368909195 3.431665269300989 3.431665269300989
50857 3284 2.387444553571073 2.927331964128233 2.927331964128233
50857 11146 1.8799042961200456 3.911788872196107 3.911788872196107
50857 4464 2.563426470678075 4.087556977893692 4.087556977893692
50857 9936 3.7653065746964183 3.8260488335423957 3.8260488335423957
50857 10316 2.3170273337244573 3.917057645209484 3.917057645209484
50857 4932 2.058921603900962 2.439489198522929 2.439489198522929
50857 19756 3.5867731170240846 4.4849212331921375 4.484921233192137

62583 7190 0.7395814084877124 2.698090628584484 2.698090628584484
62583 18908 0.8743919468623625 3.1002897473933926 3.1002897473933926
62583 17387 0.7417153314570234 2.666578246336163 2.666578246336163
62583 8839 1.4272733635363015 3.760361245257767 3.760361245257767
62583 18873 0.47784058290281434 3.4667930829130342 3.4667930829130342
62583 13793 0.2256674335733633 1.5310435374348734 1.5310435374348734
62583 5035 0.31557779149637305 2.3732688943961633 2.3732688943961633
62583 6688 0.22057746146044363 1.7238529227312847 1.7238529227312847
62583 9820 0.2785735176361123 2.886578585447049 2.886578585447049
62583 14224 0.4934375910151659 2.4535326376682485 2.4535326376682485
62583 4891 0.46454691748968224 2.8355705866748964 2.8355705866748964
62583 363 0.18101142194459927 2.781465928494205 2.781465928494205
62583 4884 1.2255648496512535 3.474294381495534 3.474294381495534
62583 13064 0.6658172055578455 3.7491216608637785 3.7491216608637785
62583 5784 0.3899628287492249 2.759777822141031 2.

64934 9834 0.28515482504524386 1.6397384857128732 1.6397384857128732
64934 15697 2.4660306312152804 2.397858745480647 2.397858745480647
64934 18976 3.1856604072185712 5.873269465575137 5.873269465575137
64934 7309 1.2306342182232226 2.2279658408729603 2.2279658408729603
64934 1534 0.5517693736797524 1.777122538002874 1.777122538002874
64934 5703 0.3991417118993709 1.530699007952799 1.530699007952799
64934 17244 0.47310588275472465 1.7223547294263082 1.7223547294263082
64934 13604 0.6282385789685144 2.120822311269843 2.120822311269843
64934 2248 0.8870227346530413 1.9920219535296428 1.9920219535296428
64934 20988 1.1140345870087496 1.9455840755185434 1.9455840755185434
64934 19482 3.1679612676471636 3.7179240378375384 3.7179240378375384
64934 15508 0.5645801143682788 1.4618217908724536 1.4618217908724536
64934 3742 0.5604416035546994 1.8029484317609858 1.8029484317609858
64934 8849 1.1447743319228254 2.07930621218561 2.07930621218561
64934 16756 0.42995411155165925 2.118274251085504 2.1

KeyboardInterrupt: 

# for each test example, sort the train indices by dtw distance to the example

In [14]:
sorted_preds = np.argsort(test_dists_npy,axis=1)

In [16]:
np.max(sorted_preds)

87553

# calculate nearest neighbors

In [18]:
from collections import Counter
pred_3nn = []
for i in range(mit_test_y.shape[0]):
    class_counts = Counter()
    for j in range(3):
        class_counts[mit_train_y_complete[sorted_preds[i][j]]] += 1
    most_com = class_counts.most_common()
    pred_3nn.append(most_com[0][0])

In [19]:
from collections import Counter
pred_5nn = []
for i in range(mit_test_y.shape[0]):
    class_counts = Counter()
    for j in range(5):
        class_counts[mit_train_y_complete[sorted_preds[i][j]]] += 1
    most_com = class_counts.most_common()
    pred_5nn.append(most_com[0][0])

In [20]:
from collections import Counter
pred_31nn = []
for i in range(mit_test_y.shape[0]):
    class_counts = Counter()
    for j in range(31):
        class_counts[mit_train_y_complete[sorted_preds[i][j]]] += 1
    most_com = class_counts.most_common()
    pred_31nn.append(most_com[0][0])

In [25]:
#1nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = mit_train_y_complete[sorted_preds[:,0]]
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[17954    84    47    16    17]
 [  132   408    12     3     1]
 [   83     7  1335    16     7]
 [   29     0    15   118     0]
 [   43     1     8     0  1556]]
accuracy: 0.9762013520920885
precision: 0.8995653060098171
recall: 0.8685558514318179
f1: 0.8834642426062617


In [21]:
#3-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = pred_3nn
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[18021    45    38     7     7]
 [  155   386    14     1     0]
 [   99     4  1317    23     5]
 [   35     0    16   111     0]
 [   53     0     7     0  1548]]
accuracy: 0.9767494975333455
precision: 0.9177700873741017
recall: 0.8492585903193983
f1: 0.8803956224881967


In [22]:
#5-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = pred_5nn
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[18014    41    47     9     7]
 [  181   360    14     1     0]
 [  105     3  1312    23     5]
 [   41     0    16   105     0]
 [   66     0     8     0  1534]]
accuracy: 0.974100127900603
precision: 0.9124002934936144
recall: 0.8299894924372454
f1: 0.8662891556806447


In [23]:
#31-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = pred_31nn
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[18003    40    64     6     5]
 [  235   316     5     0     0]
 [  209     9  1203    23     4]
 [   56     0    11    95     0]
 [  123     0     9     0  1476]]
accuracy: 0.9635026493696327
precision: 0.9046977066735538
recall: 0.7794258701223771
f1: 0.8325953547958014
