In [1]:
import numpy as np

In [2]:
mit_train = np.genfromtxt("mitbih_train.csv",delimiter=",")

In [3]:
mit_train_x_complete = mit_train[:,:-1]
mit_train_y_complete = mit_train[:,-1]

In [4]:
np.random.seed(6)
train_samp = np.random.choice(mit_train_x_complete.shape[0],replace=False,size=80000)
mit_train_x = mit_train_x_complete[train_samp]
mit_train_y = mit_train_y_complete[train_samp]
#mit_train_x = mit_train_x_complete[:]
#mit_train_y = mit_train_y_complete[:]

mit_val_x = mit_train_x_complete[np.setdiff1d(np.arange(mit_train_x_complete.shape[0]),train_samp)]
mit_val_y = mit_train_y_complete[np.setdiff1d(np.arange(mit_train_x_complete.shape[0]),train_samp)]

In [9]:
mit_test = np.genfromtxt("mitbih_test.csv",delimiter=",")

In [10]:
mit_test_x = mit_test[:,:-1]
mit_test_y = mit_test[:,-1]
mit_test_x.shape,mit_test_y.shape

((21892, 187), (21892,))

In [5]:
import sys
sys.path.append("../pytorch-softdtw-cuda")
import soft_dtw_cuda

In [12]:
sdtw = soft_dtw_cuda.SoftDTW(use_cuda=True, gamma=1e-12)

In [6]:
import torch

In [7]:
device = 'cuda'

In [8]:
batch_size = 10000
x_pieces = []
i=0
while batch_size*i < mit_train_x_complete.shape[0]:
    x_pieces.append(torch.tensor(mit_train_x_complete[batch_size*i:batch_size*(i+1)]).unsqueeze(2).to(device))
    i += 1
    print(x_pieces[-1].shape)

torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([10000, 187, 1])
torch.Size([7554, 187, 1])


In [13]:
preds = []
for i in range(mit_test_x.shape[0]):
    y = torch.tensor(mit_test_x[i:i+1]).unsqueeze(2).repeat(batch_size,1,1).to(device)
    y_lastpiece = torch.tensor(mit_test_x[i:i+1]).unsqueeze(2).repeat(x_pieces[-1].shape[0],1,1).to(device)
    pred = []
    print("start",i)
    for j,x_piece in enumerate(x_pieces[:-1]):
        #print(j,x_piece.shape)
        loss = sdtw(x_piece,y)
        pred += list(loss.detach().cpu().numpy())
    loss = sdtw(x_pieces[-1],y_lastpiece)
    pred += list(loss.detach().cpu().numpy())
    preds.append(pred)
    print(i)

start 0
0
start 1
1
start 2
2
start 3
3
start 4
4
start 5
5
start 6
6
start 7
7
start 8
8
start 9
9
start 10
10
start 11
11
start 12
12
start 13
13
start 14
14
start 15
15
start 16
16
start 17
17
start 18
18
start 19
19
start 20
20
start 21
21
start 22
22
start 23
23
start 24
24
start 25
25
start 26
26
start 27
27
start 28
28
start 29
29
start 30
30
start 31
31
start 32
32
start 33
33
start 34
34
start 35
35
start 36
36
start 37
37
start 38
38
start 39
39
start 40
40
start 41
41
start 42
42
start 43
43
start 44
44
start 45
45
start 46
46
start 47
47
start 48
48
start 49
49
start 50
50
start 51
51
start 52
52
start 53
53
start 54
54
start 55
55
start 56
56
start 57
57
start 58
58
start 59
59
start 60
60
start 61
61
start 62
62
start 63
63
start 64
64
start 65
65
start 66
66
start 67
67
start 68
68
start 69
69
start 70
70
start 71
71
start 72
72
start 73
73
start 74
74
start 75
75
start 76
76
start 77
77
start 78
78
start 79
79
start 80
80
start 81
81
start 82
82
start 83
83
start 84
84


601
start 602
602
start 603
603
start 604
604
start 605
605
start 606
606
start 607
607
start 608
608
start 609
609
start 610
610
start 611
611
start 612
612
start 613
613
start 614
614
start 615
615
start 616
616
start 617
617
start 618
618
start 619
619
start 620
620
start 621
621
start 622
622
start 623
623
start 624
624
start 625
625
start 626
626
start 627
627
start 628
628
start 629
629
start 630
630
start 631
631
start 632
632
start 633
633
start 634
634
start 635
635
start 636
636
start 637
637
start 638
638
start 639
639
start 640
640
start 641
641
start 642
642
start 643
643
start 644
644
start 645
645
start 646
646
start 647
647
start 648
648
start 649
649
start 650
650
start 651
651
start 652
652
start 653
653
start 654
654
start 655
655
start 656
656
start 657
657
start 658
658
start 659
659
start 660
660
start 661
661
start 662
662
start 663
663
start 664
664
start 665
665
start 666
666
start 667
667
start 668
668
start 669
669
start 670
670
start 671
671
start 672
672
st

1163
start 1164
1164
start 1165
1165
start 1166
1166
start 1167
1167
start 1168
1168
start 1169
1169
start 1170
1170
start 1171
1171
start 1172
1172
start 1173
1173
start 1174
1174
start 1175
1175
start 1176
1176
start 1177
1177
start 1178
1178
start 1179
1179
start 1180
1180
start 1181
1181
start 1182
1182
start 1183
1183
start 1184
1184
start 1185
1185
start 1186
1186
start 1187
1187
start 1188
1188
start 1189
1189
start 1190
1190
start 1191
1191
start 1192
1192
start 1193
1193
start 1194
1194
start 1195
1195
start 1196
1196
start 1197
1197
start 1198
1198
start 1199
1199
start 1200
1200
start 1201
1201
start 1202
1202
start 1203
1203
start 1204
1204
start 1205
1205
start 1206
1206
start 1207
1207
start 1208
1208
start 1209
1209
start 1210
1210
start 1211
1211
start 1212
1212
start 1213
1213
start 1214
1214
start 1215
1215
start 1216
1216
start 1217
1217
start 1218
1218
start 1219
1219
start 1220
1220
start 1221
1221
start 1222
1222
start 1223
1223
start 1224
1224
start 1225
1225
sta

1676
start 1677
1677
start 1678
1678
start 1679
1679
start 1680
1680
start 1681
1681
start 1682
1682
start 1683
1683
start 1684
1684
start 1685
1685
start 1686
1686
start 1687
1687
start 1688
1688
start 1689
1689
start 1690
1690
start 1691
1691
start 1692
1692
start 1693
1693
start 1694
1694
start 1695
1695
start 1696
1696
start 1697
1697
start 1698
1698
start 1699
1699
start 1700
1700
start 1701
1701
start 1702
1702
start 1703
1703
start 1704
1704
start 1705
1705
start 1706
1706
start 1707
1707
start 1708
1708
start 1709
1709
start 1710
1710
start 1711
1711
start 1712
1712
start 1713
1713
start 1714
1714
start 1715
1715
start 1716
1716
start 1717
1717
start 1718
1718
start 1719
1719
start 1720
1720
start 1721
1721
start 1722
1722
start 1723
1723
start 1724
1724
start 1725
1725
start 1726
1726
start 1727
1727
start 1728
1728
start 1729
1729
start 1730
1730
start 1731
1731
start 1732
1732
start 1733
1733
start 1734
1734
start 1735
1735
start 1736
1736
start 1737
1737
start 1738
1738
sta

2189
start 2190
2190
start 2191
2191
start 2192
2192
start 2193
2193
start 2194
2194
start 2195
2195
start 2196
2196
start 2197
2197
start 2198
2198
start 2199
2199
start 2200
2200
start 2201
2201
start 2202
2202
start 2203
2203
start 2204
2204
start 2205
2205
start 2206
2206
start 2207
2207
start 2208
2208
start 2209
2209
start 2210
2210
start 2211
2211
start 2212
2212
start 2213
2213
start 2214
2214
start 2215
2215
start 2216
2216
start 2217
2217
start 2218
2218
start 2219
2219
start 2220
2220
start 2221
2221
start 2222
2222
start 2223
2223
start 2224
2224
start 2225
2225
start 2226
2226
start 2227
2227
start 2228
2228
start 2229
2229
start 2230
2230
start 2231
2231
start 2232
2232
start 2233
2233
start 2234
2234
start 2235
2235
start 2236
2236
start 2237
2237
start 2238
2238
start 2239
2239
start 2240
2240
start 2241
2241
start 2242
2242
start 2243
2243
start 2244
2244
start 2245
2245
start 2246
2246
start 2247
2247
start 2248
2248
start 2249
2249
start 2250
2250
start 2251
2251
sta

2702
start 2703
2703
start 2704
2704
start 2705
2705
start 2706
2706
start 2707
2707
start 2708
2708
start 2709
2709
start 2710
2710
start 2711
2711
start 2712
2712
start 2713
2713
start 2714
2714
start 2715
2715
start 2716
2716
start 2717
2717
start 2718
2718
start 2719
2719
start 2720
2720
start 2721
2721
start 2722
2722
start 2723
2723
start 2724
2724
start 2725
2725
start 2726
2726
start 2727
2727
start 2728
2728
start 2729
2729
start 2730
2730
start 2731
2731
start 2732
2732
start 2733
2733
start 2734
2734
start 2735
2735
start 2736
2736
start 2737
2737
start 2738
2738
start 2739
2739
start 2740
2740
start 2741
2741
start 2742
2742
start 2743
2743
start 2744
2744
start 2745
2745
start 2746
2746
start 2747
2747
start 2748
2748
start 2749
2749
start 2750
2750
start 2751
2751
start 2752
2752
start 2753
2753
start 2754
2754
start 2755
2755
start 2756
2756
start 2757
2757
start 2758
2758
start 2759
2759
start 2760
2760
start 2761
2761
start 2762
2762
start 2763
2763
start 2764
2764
sta

3215
start 3216
3216
start 3217
3217
start 3218
3218
start 3219
3219
start 3220
3220
start 3221
3221
start 3222
3222
start 3223
3223
start 3224
3224
start 3225
3225
start 3226
3226
start 3227
3227
start 3228
3228
start 3229
3229
start 3230
3230
start 3231
3231
start 3232
3232
start 3233
3233
start 3234
3234
start 3235
3235
start 3236
3236
start 3237
3237
start 3238
3238
start 3239
3239
start 3240
3240
start 3241
3241
start 3242
3242
start 3243
3243
start 3244
3244
start 3245
3245
start 3246
3246
start 3247
3247
start 3248
3248
start 3249
3249
start 3250
3250
start 3251
3251
start 3252
3252
start 3253
3253
start 3254
3254
start 3255
3255
start 3256
3256
start 3257
3257
start 3258
3258
start 3259
3259
start 3260
3260
start 3261
3261
start 3262
3262
start 3263
3263
start 3264
3264
start 3265
3265
start 3266
3266
start 3267
3267
start 3268
3268
start 3269
3269
start 3270
3270
start 3271
3271
start 3272
3272
start 3273
3273
start 3274
3274
start 3275
3275
start 3276
3276
start 3277
3277
sta

3728
start 3729
3729
start 3730
3730
start 3731
3731
start 3732
3732
start 3733
3733
start 3734
3734
start 3735
3735
start 3736
3736
start 3737
3737
start 3738
3738
start 3739
3739
start 3740
3740
start 3741
3741
start 3742
3742
start 3743
3743
start 3744
3744
start 3745
3745
start 3746
3746
start 3747
3747
start 3748
3748
start 3749
3749
start 3750
3750
start 3751
3751
start 3752
3752
start 3753
3753
start 3754
3754
start 3755
3755
start 3756
3756
start 3757
3757
start 3758
3758
start 3759
3759
start 3760
3760
start 3761
3761
start 3762
3762
start 3763
3763
start 3764
3764
start 3765
3765
start 3766
3766
start 3767
3767
start 3768
3768
start 3769
3769
start 3770
3770
start 3771
3771
start 3772
3772
start 3773
3773
start 3774
3774
start 3775
3775
start 3776
3776
start 3777
3777
start 3778
3778
start 3779
3779
start 3780
3780
start 3781
3781
start 3782
3782
start 3783
3783
start 3784
3784
start 3785
3785
start 3786
3786
start 3787
3787
start 3788
3788
start 3789
3789
start 3790
3790
sta

4241
start 4242
4242
start 4243
4243
start 4244
4244
start 4245
4245
start 4246
4246
start 4247
4247
start 4248
4248
start 4249
4249
start 4250
4250
start 4251
4251
start 4252
4252
start 4253
4253
start 4254
4254
start 4255
4255
start 4256
4256
start 4257
4257
start 4258
4258
start 4259
4259
start 4260
4260
start 4261
4261
start 4262
4262
start 4263
4263
start 4264
4264
start 4265
4265
start 4266
4266
start 4267
4267
start 4268
4268
start 4269
4269
start 4270
4270
start 4271
4271
start 4272
4272
start 4273
4273
start 4274
4274
start 4275
4275
start 4276
4276
start 4277
4277
start 4278
4278
start 4279
4279
start 4280
4280
start 4281
4281
start 4282
4282
start 4283
4283
start 4284
4284
start 4285
4285
start 4286
4286
start 4287
4287
start 4288
4288
start 4289
4289
start 4290
4290
start 4291
4291
start 4292
4292
start 4293
4293
start 4294
4294
start 4295
4295
start 4296
4296
start 4297
4297
start 4298
4298
start 4299
4299
start 4300
4300
start 4301
4301
start 4302
4302
start 4303
4303
sta

4754
start 4755
4755
start 4756
4756
start 4757
4757
start 4758
4758
start 4759
4759
start 4760
4760
start 4761
4761
start 4762
4762
start 4763
4763
start 4764
4764
start 4765
4765
start 4766
4766
start 4767
4767
start 4768
4768
start 4769
4769
start 4770
4770
start 4771
4771
start 4772
4772
start 4773
4773
start 4774
4774
start 4775
4775
start 4776
4776
start 4777
4777
start 4778
4778
start 4779
4779
start 4780
4780
start 4781
4781
start 4782
4782
start 4783
4783
start 4784
4784
start 4785
4785
start 4786
4786
start 4787
4787
start 4788
4788
start 4789
4789
start 4790
4790
start 4791
4791
start 4792
4792
start 4793
4793
start 4794
4794
start 4795
4795
start 4796
4796
start 4797
4797
start 4798
4798
start 4799
4799
start 4800
4800
start 4801
4801
start 4802
4802
start 4803
4803
start 4804
4804
start 4805
4805
start 4806
4806
start 4807
4807
start 4808
4808
start 4809
4809
start 4810
4810
start 4811
4811
start 4812
4812
start 4813
4813
start 4814
4814
start 4815
4815
start 4816
4816
sta

5267
start 5268
5268
start 5269
5269
start 5270
5270
start 5271
5271
start 5272
5272
start 5273
5273
start 5274
5274
start 5275
5275
start 5276
5276
start 5277
5277
start 5278
5278
start 5279
5279
start 5280
5280
start 5281
5281
start 5282
5282
start 5283
5283
start 5284
5284
start 5285
5285
start 5286
5286
start 5287
5287
start 5288
5288
start 5289
5289
start 5290
5290
start 5291
5291
start 5292
5292
start 5293
5293
start 5294
5294
start 5295
5295
start 5296
5296
start 5297
5297
start 5298
5298
start 5299
5299
start 5300
5300
start 5301
5301
start 5302
5302
start 5303
5303
start 5304
5304
start 5305
5305
start 5306
5306
start 5307
5307
start 5308
5308
start 5309
5309
start 5310
5310
start 5311
5311
start 5312
5312
start 5313
5313
start 5314
5314
start 5315
5315
start 5316
5316
start 5317
5317
start 5318
5318
start 5319
5319
start 5320
5320
start 5321
5321
start 5322
5322
start 5323
5323
start 5324
5324
start 5325
5325
start 5326
5326
start 5327
5327
start 5328
5328
start 5329
5329
sta

5780
start 5781
5781
start 5782
5782
start 5783
5783
start 5784
5784
start 5785
5785
start 5786
5786
start 5787
5787
start 5788
5788
start 5789
5789
start 5790
5790
start 5791
5791
start 5792
5792
start 5793
5793
start 5794
5794
start 5795
5795
start 5796
5796
start 5797
5797
start 5798
5798
start 5799
5799
start 5800
5800
start 5801
5801
start 5802
5802
start 5803
5803
start 5804
5804
start 5805
5805
start 5806
5806
start 5807
5807
start 5808
5808
start 5809
5809
start 5810
5810
start 5811
5811
start 5812
5812
start 5813
5813
start 5814
5814
start 5815
5815
start 5816
5816
start 5817
5817
start 5818
5818
start 5819
5819
start 5820
5820
start 5821
5821
start 5822
5822
start 5823
5823
start 5824
5824
start 5825
5825
start 5826
5826
start 5827
5827
start 5828
5828
start 5829
5829
start 5830
5830
start 5831
5831
start 5832
5832
start 5833
5833
start 5834
5834
start 5835
5835
start 5836
5836
start 5837
5837
start 5838
5838
start 5839
5839
start 5840
5840
start 5841
5841
start 5842
5842
sta

6293
start 6294
6294
start 6295
6295
start 6296
6296
start 6297
6297
start 6298
6298
start 6299
6299
start 6300
6300
start 6301
6301
start 6302
6302
start 6303
6303
start 6304
6304
start 6305
6305
start 6306
6306
start 6307
6307
start 6308
6308
start 6309
6309
start 6310
6310
start 6311
6311
start 6312
6312
start 6313
6313
start 6314
6314
start 6315
6315
start 6316
6316
start 6317
6317
start 6318
6318
start 6319
6319
start 6320
6320
start 6321
6321
start 6322
6322
start 6323
6323
start 6324
6324
start 6325
6325
start 6326
6326
start 6327
6327
start 6328
6328
start 6329
6329
start 6330
6330
start 6331
6331
start 6332
6332
start 6333
6333
start 6334
6334
start 6335
6335
start 6336
6336
start 6337
6337
start 6338
6338
start 6339
6339
start 6340
6340
start 6341
6341
start 6342
6342
start 6343
6343
start 6344
6344
start 6345
6345
start 6346
6346
start 6347
6347
start 6348
6348
start 6349
6349
start 6350
6350
start 6351
6351
start 6352
6352
start 6353
6353
start 6354
6354
start 6355
6355
sta

6806
start 6807
6807
start 6808
6808
start 6809
6809
start 6810
6810
start 6811
6811
start 6812
6812
start 6813
6813
start 6814
6814
start 6815
6815
start 6816
6816
start 6817
6817
start 6818
6818
start 6819
6819
start 6820
6820
start 6821
6821
start 6822
6822
start 6823
6823
start 6824
6824
start 6825
6825
start 6826
6826
start 6827
6827
start 6828
6828
start 6829
6829
start 6830
6830
start 6831
6831
start 6832
6832
start 6833
6833
start 6834
6834
start 6835
6835
start 6836
6836
start 6837
6837
start 6838
6838
start 6839
6839
start 6840
6840
start 6841
6841
start 6842
6842
start 6843
6843
start 6844
6844
start 6845
6845
start 6846
6846
start 6847
6847
start 6848
6848
start 6849
6849
start 6850
6850
start 6851
6851
start 6852
6852
start 6853
6853
start 6854
6854
start 6855
6855
start 6856
6856
start 6857
6857
start 6858
6858
start 6859
6859
start 6860
6860
start 6861
6861
start 6862
6862
start 6863
6863
start 6864
6864
start 6865
6865
start 6866
6866
start 6867
6867
start 6868
6868
sta

7319
start 7320
7320
start 7321
7321
start 7322
7322
start 7323
7323
start 7324
7324
start 7325
7325
start 7326
7326
start 7327
7327
start 7328
7328
start 7329
7329
start 7330
7330
start 7331
7331
start 7332
7332
start 7333
7333
start 7334
7334
start 7335
7335
start 7336
7336
start 7337
7337
start 7338
7338
start 7339
7339
start 7340
7340
start 7341
7341
start 7342
7342
start 7343
7343
start 7344
7344
start 7345
7345
start 7346
7346
start 7347
7347
start 7348
7348
start 7349
7349
start 7350
7350
start 7351
7351
start 7352
7352
start 7353
7353
start 7354
7354
start 7355
7355
start 7356
7356
start 7357
7357
start 7358
7358
start 7359
7359
start 7360
7360
start 7361
7361
start 7362
7362
start 7363
7363
start 7364
7364
start 7365
7365
start 7366
7366
start 7367
7367
start 7368
7368
start 7369
7369
start 7370
7370
start 7371
7371
start 7372
7372
start 7373
7373
start 7374
7374
start 7375
7375
start 7376
7376
start 7377
7377
start 7378
7378
start 7379
7379
start 7380
7380
start 7381
7381
sta

7832
start 7833
7833
start 7834
7834
start 7835
7835
start 7836
7836
start 7837
7837
start 7838
7838
start 7839
7839
start 7840
7840
start 7841
7841
start 7842
7842
start 7843
7843
start 7844
7844
start 7845
7845
start 7846
7846
start 7847
7847
start 7848
7848
start 7849
7849
start 7850
7850
start 7851
7851
start 7852
7852
start 7853
7853
start 7854
7854
start 7855
7855
start 7856
7856
start 7857
7857
start 7858
7858
start 7859
7859
start 7860
7860
start 7861
7861
start 7862
7862
start 7863
7863
start 7864
7864
start 7865
7865
start 7866
7866
start 7867
7867
start 7868
7868
start 7869
7869
start 7870
7870
start 7871
7871
start 7872
7872
start 7873
7873
start 7874
7874
start 7875
7875
start 7876
7876
start 7877
7877
start 7878
7878
start 7879
7879
start 7880
7880
start 7881
7881
start 7882
7882
start 7883
7883
start 7884
7884
start 7885
7885
start 7886
7886
start 7887
7887
start 7888
7888
start 7889
7889
start 7890
7890
start 7891
7891
start 7892
7892
start 7893
7893
start 7894
7894
sta

8345
start 8346
8346
start 8347
8347
start 8348
8348
start 8349
8349
start 8350
8350
start 8351
8351
start 8352
8352
start 8353
8353
start 8354
8354
start 8355
8355
start 8356
8356
start 8357
8357
start 8358
8358
start 8359
8359
start 8360
8360
start 8361
8361
start 8362
8362
start 8363
8363
start 8364
8364
start 8365
8365
start 8366
8366
start 8367
8367
start 8368
8368
start 8369
8369
start 8370
8370
start 8371
8371
start 8372
8372
start 8373
8373
start 8374
8374
start 8375
8375
start 8376
8376
start 8377
8377
start 8378
8378
start 8379
8379
start 8380
8380
start 8381
8381
start 8382
8382
start 8383
8383
start 8384
8384
start 8385
8385
start 8386
8386
start 8387
8387
start 8388
8388
start 8389
8389
start 8390
8390
start 8391
8391
start 8392
8392
start 8393
8393
start 8394
8394
start 8395
8395
start 8396
8396
start 8397
8397
start 8398
8398
start 8399
8399
start 8400
8400
start 8401
8401
start 8402
8402
start 8403
8403
start 8404
8404
start 8405
8405
start 8406
8406
start 8407
8407
sta

8858
start 8859
8859
start 8860
8860
start 8861
8861
start 8862
8862
start 8863
8863
start 8864
8864
start 8865
8865
start 8866
8866
start 8867
8867
start 8868
8868
start 8869
8869
start 8870
8870
start 8871
8871
start 8872
8872
start 8873
8873
start 8874
8874
start 8875
8875
start 8876
8876
start 8877
8877
start 8878
8878
start 8879
8879
start 8880
8880
start 8881
8881
start 8882
8882
start 8883
8883
start 8884
8884
start 8885
8885
start 8886
8886
start 8887
8887
start 8888
8888
start 8889
8889
start 8890
8890
start 8891
8891
start 8892
8892
start 8893
8893
start 8894
8894
start 8895
8895
start 8896
8896
start 8897
8897
start 8898
8898
start 8899
8899
start 8900
8900
start 8901
8901
start 8902
8902
start 8903
8903
start 8904
8904
start 8905
8905
start 8906
8906
start 8907
8907
start 8908
8908
start 8909
8909
start 8910
8910
start 8911
8911
start 8912
8912
start 8913
8913
start 8914
8914
start 8915
8915
start 8916
8916
start 8917
8917
start 8918
8918
start 8919
8919
start 8920
8920
sta

9371
start 9372
9372
start 9373
9373
start 9374
9374
start 9375
9375
start 9376
9376
start 9377
9377
start 9378
9378
start 9379
9379
start 9380
9380
start 9381
9381
start 9382
9382
start 9383
9383
start 9384
9384
start 9385
9385
start 9386
9386
start 9387
9387
start 9388
9388
start 9389
9389
start 9390
9390
start 9391
9391
start 9392
9392
start 9393
9393
start 9394
9394
start 9395
9395
start 9396
9396
start 9397
9397
start 9398
9398
start 9399
9399
start 9400
9400
start 9401
9401
start 9402
9402
start 9403
9403
start 9404
9404
start 9405
9405
start 9406
9406
start 9407
9407
start 9408
9408
start 9409
9409
start 9410
9410
start 9411
9411
start 9412
9412
start 9413
9413
start 9414
9414
start 9415
9415
start 9416
9416
start 9417
9417
start 9418
9418
start 9419
9419
start 9420
9420
start 9421
9421
start 9422
9422
start 9423
9423
start 9424
9424
start 9425
9425
start 9426
9426
start 9427
9427
start 9428
9428
start 9429
9429
start 9430
9430
start 9431
9431
start 9432
9432
start 9433
9433
sta

9884
start 9885
9885
start 9886
9886
start 9887
9887
start 9888
9888
start 9889
9889
start 9890
9890
start 9891
9891
start 9892
9892
start 9893
9893
start 9894
9894
start 9895
9895
start 9896
9896
start 9897
9897
start 9898
9898
start 9899
9899
start 9900
9900
start 9901
9901
start 9902
9902
start 9903
9903
start 9904
9904
start 9905
9905
start 9906
9906
start 9907
9907
start 9908
9908
start 9909
9909
start 9910
9910
start 9911
9911
start 9912
9912
start 9913
9913
start 9914
9914
start 9915
9915
start 9916
9916
start 9917
9917
start 9918
9918
start 9919
9919
start 9920
9920
start 9921
9921
start 9922
9922
start 9923
9923
start 9924
9924
start 9925
9925
start 9926
9926
start 9927
9927
start 9928
9928
start 9929
9929
start 9930
9930
start 9931
9931
start 9932
9932
start 9933
9933
start 9934
9934
start 9935
9935
start 9936
9936
start 9937
9937
start 9938
9938
start 9939
9939
start 9940
9940
start 9941
9941
start 9942
9942
start 9943
9943
start 9944
9944
start 9945
9945
start 9946
9946
sta

10352
start 10353
10353
start 10354
10354
start 10355
10355
start 10356
10356
start 10357
10357
start 10358
10358
start 10359
10359
start 10360
10360
start 10361
10361
start 10362
10362
start 10363
10363
start 10364
10364
start 10365
10365
start 10366
10366
start 10367
10367
start 10368
10368
start 10369
10369
start 10370
10370
start 10371
10371
start 10372
10372
start 10373
10373
start 10374
10374
start 10375
10375
start 10376
10376
start 10377
10377
start 10378
10378
start 10379
10379
start 10380
10380
start 10381
10381
start 10382
10382
start 10383
10383
start 10384
10384
start 10385
10385
start 10386
10386
start 10387
10387
start 10388
10388
start 10389
10389
start 10390
10390
start 10391
10391
start 10392
10392
start 10393
10393
start 10394
10394
start 10395
10395
start 10396
10396
start 10397
10397
start 10398
10398
start 10399
10399
start 10400
10400
start 10401
10401
start 10402
10402
start 10403
10403
start 10404
10404
start 10405
10405
start 10406
10406
start 10407
10407
star

10808
start 10809
10809
start 10810
10810
start 10811
10811
start 10812
10812
start 10813
10813
start 10814
10814
start 10815
10815
start 10816
10816
start 10817
10817
start 10818
10818
start 10819
10819
start 10820
10820
start 10821
10821
start 10822
10822
start 10823
10823
start 10824
10824
start 10825
10825
start 10826
10826
start 10827
10827
start 10828
10828
start 10829
10829
start 10830
10830
start 10831
10831
start 10832
10832
start 10833
10833
start 10834
10834
start 10835
10835
start 10836
10836
start 10837
10837
start 10838
10838
start 10839
10839
start 10840
10840
start 10841
10841
start 10842
10842
start 10843
10843
start 10844
10844
start 10845
10845
start 10846
10846
start 10847
10847
start 10848
10848
start 10849
10849
start 10850
10850
start 10851
10851
start 10852
10852
start 10853
10853
start 10854
10854
start 10855
10855
start 10856
10856
start 10857
10857
start 10858
10858
start 10859
10859
start 10860
10860
start 10861
10861
start 10862
10862
start 10863
10863
star

11264
start 11265
11265
start 11266
11266
start 11267
11267
start 11268
11268
start 11269
11269
start 11270
11270
start 11271
11271
start 11272
11272
start 11273
11273
start 11274
11274
start 11275
11275
start 11276
11276
start 11277
11277
start 11278
11278
start 11279
11279
start 11280
11280
start 11281
11281
start 11282
11282
start 11283
11283
start 11284
11284
start 11285
11285
start 11286
11286
start 11287
11287
start 11288
11288
start 11289
11289
start 11290
11290
start 11291
11291
start 11292
11292
start 11293
11293
start 11294
11294
start 11295
11295
start 11296
11296
start 11297
11297
start 11298
11298
start 11299
11299
start 11300
11300
start 11301
11301
start 11302
11302
start 11303
11303
start 11304
11304
start 11305
11305
start 11306
11306
start 11307
11307
start 11308
11308
start 11309
11309
start 11310
11310
start 11311
11311
start 11312
11312
start 11313
11313
start 11314
11314
start 11315
11315
start 11316
11316
start 11317
11317
start 11318
11318
start 11319
11319
star

11720
start 11721
11721
start 11722
11722
start 11723
11723
start 11724
11724
start 11725
11725
start 11726
11726
start 11727
11727
start 11728
11728
start 11729
11729
start 11730
11730
start 11731
11731
start 11732
11732
start 11733
11733
start 11734
11734
start 11735
11735
start 11736
11736
start 11737
11737
start 11738
11738
start 11739
11739
start 11740
11740
start 11741
11741
start 11742
11742
start 11743
11743
start 11744
11744
start 11745
11745
start 11746
11746
start 11747
11747
start 11748
11748
start 11749
11749
start 11750
11750
start 11751
11751
start 11752
11752
start 11753
11753
start 11754
11754
start 11755
11755
start 11756
11756
start 11757
11757
start 11758
11758
start 11759
11759
start 11760
11760
start 11761
11761
start 11762
11762
start 11763
11763
start 11764
11764
start 11765
11765
start 11766
11766
start 11767
11767
start 11768
11768
start 11769
11769
start 11770
11770
start 11771
11771
start 11772
11772
start 11773
11773
start 11774
11774
start 11775
11775
star

12176
start 12177
12177
start 12178
12178
start 12179
12179
start 12180
12180
start 12181
12181
start 12182
12182
start 12183
12183
start 12184
12184
start 12185
12185
start 12186
12186
start 12187
12187
start 12188
12188
start 12189
12189
start 12190
12190
start 12191
12191
start 12192
12192
start 12193
12193
start 12194
12194
start 12195
12195
start 12196
12196
start 12197
12197
start 12198
12198
start 12199
12199
start 12200
12200
start 12201
12201
start 12202
12202
start 12203
12203
start 12204
12204
start 12205
12205
start 12206
12206
start 12207
12207
start 12208
12208
start 12209
12209
start 12210
12210
start 12211
12211
start 12212
12212
start 12213
12213
start 12214
12214
start 12215
12215
start 12216
12216
start 12217
12217
start 12218
12218
start 12219
12219
start 12220
12220
start 12221
12221
start 12222
12222
start 12223
12223
start 12224
12224
start 12225
12225
start 12226
12226
start 12227
12227
start 12228
12228
start 12229
12229
start 12230
12230
start 12231
12231
star

12632
start 12633
12633
start 12634
12634
start 12635
12635
start 12636
12636
start 12637
12637
start 12638
12638
start 12639
12639
start 12640
12640
start 12641
12641
start 12642
12642
start 12643
12643
start 12644
12644
start 12645
12645
start 12646
12646
start 12647
12647
start 12648
12648
start 12649
12649
start 12650
12650
start 12651
12651
start 12652
12652
start 12653
12653
start 12654
12654
start 12655
12655
start 12656
12656
start 12657
12657
start 12658
12658
start 12659
12659
start 12660
12660
start 12661
12661
start 12662
12662
start 12663
12663
start 12664
12664
start 12665
12665
start 12666
12666
start 12667
12667
start 12668
12668
start 12669
12669
start 12670
12670
start 12671
12671
start 12672
12672
start 12673
12673
start 12674
12674
start 12675
12675
start 12676
12676
start 12677
12677
start 12678
12678
start 12679
12679
start 12680
12680
start 12681
12681
start 12682
12682
start 12683
12683
start 12684
12684
start 12685
12685
start 12686
12686
start 12687
12687
star

13088
start 13089
13089
start 13090
13090
start 13091
13091
start 13092
13092
start 13093
13093
start 13094
13094
start 13095
13095
start 13096
13096
start 13097
13097
start 13098
13098
start 13099
13099
start 13100
13100
start 13101
13101
start 13102
13102
start 13103
13103
start 13104
13104
start 13105
13105
start 13106
13106
start 13107
13107
start 13108
13108
start 13109
13109
start 13110
13110
start 13111
13111
start 13112
13112
start 13113
13113
start 13114
13114
start 13115
13115
start 13116
13116
start 13117
13117
start 13118
13118
start 13119
13119
start 13120
13120
start 13121
13121
start 13122
13122
start 13123
13123
start 13124
13124
start 13125
13125
start 13126
13126
start 13127
13127
start 13128
13128
start 13129
13129
start 13130
13130
start 13131
13131
start 13132
13132
start 13133
13133
start 13134
13134
start 13135
13135
start 13136
13136
start 13137
13137
start 13138
13138
start 13139
13139
start 13140
13140
start 13141
13141
start 13142
13142
start 13143
13143
star

13544
start 13545
13545
start 13546
13546
start 13547
13547
start 13548
13548
start 13549
13549
start 13550
13550
start 13551
13551
start 13552
13552
start 13553
13553
start 13554
13554
start 13555
13555
start 13556
13556
start 13557
13557
start 13558
13558
start 13559
13559
start 13560
13560
start 13561
13561
start 13562
13562
start 13563
13563
start 13564
13564
start 13565
13565
start 13566
13566
start 13567
13567
start 13568
13568
start 13569
13569
start 13570
13570
start 13571
13571
start 13572
13572
start 13573
13573
start 13574
13574
start 13575
13575
start 13576
13576
start 13577
13577
start 13578
13578
start 13579
13579
start 13580
13580
start 13581
13581
start 13582
13582
start 13583
13583
start 13584
13584
start 13585
13585
start 13586
13586
start 13587
13587
start 13588
13588
start 13589
13589
start 13590
13590
start 13591
13591
start 13592
13592
start 13593
13593
start 13594
13594
start 13595
13595
start 13596
13596
start 13597
13597
start 13598
13598
start 13599
13599
star

14000
start 14001
14001
start 14002
14002
start 14003
14003
start 14004
14004
start 14005
14005
start 14006
14006
start 14007
14007
start 14008
14008
start 14009
14009
start 14010
14010
start 14011
14011
start 14012
14012
start 14013
14013
start 14014
14014
start 14015
14015
start 14016
14016
start 14017
14017
start 14018
14018
start 14019
14019
start 14020
14020
start 14021
14021
start 14022
14022
start 14023
14023
start 14024
14024
start 14025
14025
start 14026
14026
start 14027
14027
start 14028
14028
start 14029
14029
start 14030
14030
start 14031
14031
start 14032
14032
start 14033
14033
start 14034
14034
start 14035
14035
start 14036
14036
start 14037
14037
start 14038
14038
start 14039
14039
start 14040
14040
start 14041
14041
start 14042
14042
start 14043
14043
start 14044
14044
start 14045
14045
start 14046
14046
start 14047
14047
start 14048
14048
start 14049
14049
start 14050
14050
start 14051
14051
start 14052
14052
start 14053
14053
start 14054
14054
start 14055
14055
star

14456
start 14457
14457
start 14458
14458
start 14459
14459
start 14460
14460
start 14461
14461
start 14462
14462
start 14463
14463
start 14464
14464
start 14465
14465
start 14466
14466
start 14467
14467
start 14468
14468
start 14469
14469
start 14470
14470
start 14471
14471
start 14472
14472
start 14473
14473
start 14474
14474
start 14475
14475
start 14476
14476
start 14477
14477
start 14478
14478
start 14479
14479
start 14480
14480
start 14481
14481
start 14482
14482
start 14483
14483
start 14484
14484
start 14485
14485
start 14486
14486
start 14487
14487
start 14488
14488
start 14489
14489
start 14490
14490
start 14491
14491
start 14492
14492
start 14493
14493
start 14494
14494
start 14495
14495
start 14496
14496
start 14497
14497
start 14498
14498
start 14499
14499
start 14500
14500
start 14501
14501
start 14502
14502
start 14503
14503
start 14504
14504
start 14505
14505
start 14506
14506
start 14507
14507
start 14508
14508
start 14509
14509
start 14510
14510
start 14511
14511
star

14912
start 14913
14913
start 14914
14914
start 14915
14915
start 14916
14916
start 14917
14917
start 14918
14918
start 14919
14919
start 14920
14920
start 14921
14921
start 14922
14922
start 14923
14923
start 14924
14924
start 14925
14925
start 14926
14926
start 14927
14927
start 14928
14928
start 14929
14929
start 14930
14930
start 14931
14931
start 14932
14932
start 14933
14933
start 14934
14934
start 14935
14935
start 14936
14936
start 14937
14937
start 14938
14938
start 14939
14939
start 14940
14940
start 14941
14941
start 14942
14942
start 14943
14943
start 14944
14944
start 14945
14945
start 14946
14946
start 14947
14947
start 14948
14948
start 14949
14949
start 14950
14950
start 14951
14951
start 14952
14952
start 14953
14953
start 14954
14954
start 14955
14955
start 14956
14956
start 14957
14957
start 14958
14958
start 14959
14959
start 14960
14960
start 14961
14961
start 14962
14962
start 14963
14963
start 14964
14964
start 14965
14965
start 14966
14966
start 14967
14967
star

15368
start 15369
15369
start 15370
15370
start 15371
15371
start 15372
15372
start 15373
15373
start 15374
15374
start 15375
15375
start 15376
15376
start 15377
15377
start 15378
15378
start 15379
15379
start 15380
15380
start 15381
15381
start 15382
15382
start 15383
15383
start 15384
15384
start 15385
15385
start 15386
15386
start 15387
15387
start 15388
15388
start 15389
15389
start 15390
15390
start 15391
15391
start 15392
15392
start 15393
15393
start 15394
15394
start 15395
15395
start 15396
15396
start 15397
15397
start 15398
15398
start 15399
15399
start 15400
15400
start 15401
15401
start 15402
15402
start 15403
15403
start 15404
15404
start 15405
15405
start 15406
15406
start 15407
15407
start 15408
15408
start 15409
15409
start 15410
15410
start 15411
15411
start 15412
15412
start 15413
15413
start 15414
15414
start 15415
15415
start 15416
15416
start 15417
15417
start 15418
15418
start 15419
15419
start 15420
15420
start 15421
15421
start 15422
15422
start 15423
15423
star

15824
start 15825
15825
start 15826
15826
start 15827
15827
start 15828
15828
start 15829
15829
start 15830
15830
start 15831
15831
start 15832
15832
start 15833
15833
start 15834
15834
start 15835
15835
start 15836
15836
start 15837
15837
start 15838
15838
start 15839
15839
start 15840
15840
start 15841
15841
start 15842
15842
start 15843
15843
start 15844
15844
start 15845
15845
start 15846
15846
start 15847
15847
start 15848
15848
start 15849
15849
start 15850
15850
start 15851
15851
start 15852
15852
start 15853
15853
start 15854
15854
start 15855
15855
start 15856
15856
start 15857
15857
start 15858
15858
start 15859
15859
start 15860
15860
start 15861
15861
start 15862
15862
start 15863
15863
start 15864
15864
start 15865
15865
start 15866
15866
start 15867
15867
start 15868
15868
start 15869
15869
start 15870
15870
start 15871
15871
start 15872
15872
start 15873
15873
start 15874
15874
start 15875
15875
start 15876
15876
start 15877
15877
start 15878
15878
start 15879
15879
star

16280
start 16281
16281
start 16282
16282
start 16283
16283
start 16284
16284
start 16285
16285
start 16286
16286
start 16287
16287
start 16288
16288
start 16289
16289
start 16290
16290
start 16291
16291
start 16292
16292
start 16293
16293
start 16294
16294
start 16295
16295
start 16296
16296
start 16297
16297
start 16298
16298
start 16299
16299
start 16300
16300
start 16301
16301
start 16302
16302
start 16303
16303
start 16304
16304
start 16305
16305
start 16306
16306
start 16307
16307
start 16308
16308
start 16309
16309
start 16310
16310
start 16311
16311
start 16312
16312
start 16313
16313
start 16314
16314
start 16315
16315
start 16316
16316
start 16317
16317
start 16318
16318
start 16319
16319
start 16320
16320
start 16321
16321
start 16322
16322
start 16323
16323
start 16324
16324
start 16325
16325
start 16326
16326
start 16327
16327
start 16328
16328
start 16329
16329
start 16330
16330
start 16331
16331
start 16332
16332
start 16333
16333
start 16334
16334
start 16335
16335
star

16736
start 16737
16737
start 16738
16738
start 16739
16739
start 16740
16740
start 16741
16741
start 16742
16742
start 16743
16743
start 16744
16744
start 16745
16745
start 16746
16746
start 16747
16747
start 16748
16748
start 16749
16749
start 16750
16750
start 16751
16751
start 16752
16752
start 16753
16753
start 16754
16754
start 16755
16755
start 16756
16756
start 16757
16757
start 16758
16758
start 16759
16759
start 16760
16760
start 16761
16761
start 16762
16762
start 16763
16763
start 16764
16764
start 16765
16765
start 16766
16766
start 16767
16767
start 16768
16768
start 16769
16769
start 16770
16770
start 16771
16771
start 16772
16772
start 16773
16773
start 16774
16774
start 16775
16775
start 16776
16776
start 16777
16777
start 16778
16778
start 16779
16779
start 16780
16780
start 16781
16781
start 16782
16782
start 16783
16783
start 16784
16784
start 16785
16785
start 16786
16786
start 16787
16787
start 16788
16788
start 16789
16789
start 16790
16790
start 16791
16791
star

17192
start 17193
17193
start 17194
17194
start 17195
17195
start 17196
17196
start 17197
17197
start 17198
17198
start 17199
17199
start 17200
17200
start 17201
17201
start 17202
17202
start 17203
17203
start 17204
17204
start 17205
17205
start 17206
17206
start 17207
17207
start 17208
17208
start 17209
17209
start 17210
17210
start 17211
17211
start 17212
17212
start 17213
17213
start 17214
17214
start 17215
17215
start 17216
17216
start 17217
17217
start 17218
17218
start 17219
17219
start 17220
17220
start 17221
17221
start 17222
17222
start 17223
17223
start 17224
17224
start 17225
17225
start 17226
17226
start 17227
17227
start 17228
17228
start 17229
17229
start 17230
17230
start 17231
17231
start 17232
17232
start 17233
17233
start 17234
17234
start 17235
17235
start 17236
17236
start 17237
17237
start 17238
17238
start 17239
17239
start 17240
17240
start 17241
17241
start 17242
17242
start 17243
17243
start 17244
17244
start 17245
17245
start 17246
17246
start 17247
17247
star

17648
start 17649
17649
start 17650
17650
start 17651
17651
start 17652
17652
start 17653
17653
start 17654
17654
start 17655
17655
start 17656
17656
start 17657
17657
start 17658
17658
start 17659
17659
start 17660
17660
start 17661
17661
start 17662
17662
start 17663
17663
start 17664
17664
start 17665
17665
start 17666
17666
start 17667
17667
start 17668
17668
start 17669
17669
start 17670
17670
start 17671
17671
start 17672
17672
start 17673
17673
start 17674
17674
start 17675
17675
start 17676
17676
start 17677
17677
start 17678
17678
start 17679
17679
start 17680
17680
start 17681
17681
start 17682
17682
start 17683
17683
start 17684
17684
start 17685
17685
start 17686
17686
start 17687
17687
start 17688
17688
start 17689
17689
start 17690
17690
start 17691
17691
start 17692
17692
start 17693
17693
start 17694
17694
start 17695
17695
start 17696
17696
start 17697
17697
start 17698
17698
start 17699
17699
start 17700
17700
start 17701
17701
start 17702
17702
start 17703
17703
star

18104
start 18105
18105
start 18106
18106
start 18107
18107
start 18108
18108
start 18109
18109
start 18110
18110
start 18111
18111
start 18112
18112
start 18113
18113
start 18114
18114
start 18115
18115
start 18116
18116
start 18117
18117
start 18118
18118
start 18119
18119
start 18120
18120
start 18121
18121
start 18122
18122
start 18123
18123
start 18124
18124
start 18125
18125
start 18126
18126
start 18127
18127
start 18128
18128
start 18129
18129
start 18130
18130
start 18131
18131
start 18132
18132
start 18133
18133
start 18134
18134
start 18135
18135
start 18136
18136
start 18137
18137
start 18138
18138
start 18139
18139
start 18140
18140
start 18141
18141
start 18142
18142
start 18143
18143
start 18144
18144
start 18145
18145
start 18146
18146
start 18147
18147
start 18148
18148
start 18149
18149
start 18150
18150
start 18151
18151
start 18152
18152
start 18153
18153
start 18154
18154
start 18155
18155
start 18156
18156
start 18157
18157
start 18158
18158
start 18159
18159
star

18560
start 18561
18561
start 18562
18562
start 18563
18563
start 18564
18564
start 18565
18565
start 18566
18566
start 18567
18567
start 18568
18568
start 18569
18569
start 18570
18570
start 18571
18571
start 18572
18572
start 18573
18573
start 18574
18574
start 18575
18575
start 18576
18576
start 18577
18577
start 18578
18578
start 18579
18579
start 18580
18580
start 18581
18581
start 18582
18582
start 18583
18583
start 18584
18584
start 18585
18585
start 18586
18586
start 18587
18587
start 18588
18588
start 18589
18589
start 18590
18590
start 18591
18591
start 18592
18592
start 18593
18593
start 18594
18594
start 18595
18595
start 18596
18596
start 18597
18597
start 18598
18598
start 18599
18599
start 18600
18600
start 18601
18601
start 18602
18602
start 18603
18603
start 18604
18604
start 18605
18605
start 18606
18606
start 18607
18607
start 18608
18608
start 18609
18609
start 18610
18610
start 18611
18611
start 18612
18612
start 18613
18613
start 18614
18614
start 18615
18615
star

19016
start 19017
19017
start 19018
19018
start 19019
19019
start 19020
19020
start 19021
19021
start 19022
19022
start 19023
19023
start 19024
19024
start 19025
19025
start 19026
19026
start 19027
19027
start 19028
19028
start 19029
19029
start 19030
19030
start 19031
19031
start 19032
19032
start 19033
19033
start 19034
19034
start 19035
19035
start 19036
19036
start 19037
19037
start 19038
19038
start 19039
19039
start 19040
19040
start 19041
19041
start 19042
19042
start 19043
19043
start 19044
19044
start 19045
19045
start 19046
19046
start 19047
19047
start 19048
19048
start 19049
19049
start 19050
19050
start 19051
19051
start 19052
19052
start 19053
19053
start 19054
19054
start 19055
19055
start 19056
19056
start 19057
19057
start 19058
19058
start 19059
19059
start 19060
19060
start 19061
19061
start 19062
19062
start 19063
19063
start 19064
19064
start 19065
19065
start 19066
19066
start 19067
19067
start 19068
19068
start 19069
19069
start 19070
19070
start 19071
19071
star

19472
start 19473
19473
start 19474
19474
start 19475
19475
start 19476
19476
start 19477
19477
start 19478
19478
start 19479
19479
start 19480
19480
start 19481
19481
start 19482
19482
start 19483
19483
start 19484
19484
start 19485
19485
start 19486
19486
start 19487
19487
start 19488
19488
start 19489
19489
start 19490
19490
start 19491
19491
start 19492
19492
start 19493
19493
start 19494
19494
start 19495
19495
start 19496
19496
start 19497
19497
start 19498
19498
start 19499
19499
start 19500
19500
start 19501
19501
start 19502
19502
start 19503
19503
start 19504
19504
start 19505
19505
start 19506
19506
start 19507
19507
start 19508
19508
start 19509
19509
start 19510
19510
start 19511
19511
start 19512
19512
start 19513
19513
start 19514
19514
start 19515
19515
start 19516
19516
start 19517
19517
start 19518
19518
start 19519
19519
start 19520
19520
start 19521
19521
start 19522
19522
start 19523
19523
start 19524
19524
start 19525
19525
start 19526
19526
start 19527
19527
star

19928
start 19929
19929
start 19930
19930
start 19931
19931
start 19932
19932
start 19933
19933
start 19934
19934
start 19935
19935
start 19936
19936
start 19937
19937
start 19938
19938
start 19939
19939
start 19940
19940
start 19941
19941
start 19942
19942
start 19943
19943
start 19944
19944
start 19945
19945
start 19946
19946
start 19947
19947
start 19948
19948
start 19949
19949
start 19950
19950
start 19951
19951
start 19952
19952
start 19953
19953
start 19954
19954
start 19955
19955
start 19956
19956
start 19957
19957
start 19958
19958
start 19959
19959
start 19960
19960
start 19961
19961
start 19962
19962
start 19963
19963
start 19964
19964
start 19965
19965
start 19966
19966
start 19967
19967
start 19968
19968
start 19969
19969
start 19970
19970
start 19971
19971
start 19972
19972
start 19973
19973
start 19974
19974
start 19975
19975
start 19976
19976
start 19977
19977
start 19978
19978
start 19979
19979
start 19980
19980
start 19981
19981
start 19982
19982
start 19983
19983
star

20384
start 20385
20385
start 20386
20386
start 20387
20387
start 20388
20388
start 20389
20389
start 20390
20390
start 20391
20391
start 20392
20392
start 20393
20393
start 20394
20394
start 20395
20395
start 20396
20396
start 20397
20397
start 20398
20398
start 20399
20399
start 20400
20400
start 20401
20401
start 20402
20402
start 20403
20403
start 20404
20404
start 20405
20405
start 20406
20406
start 20407
20407
start 20408
20408
start 20409
20409
start 20410
20410
start 20411
20411
start 20412
20412
start 20413
20413
start 20414
20414
start 20415
20415
start 20416
20416
start 20417
20417
start 20418
20418
start 20419
20419
start 20420
20420
start 20421
20421
start 20422
20422
start 20423
20423
start 20424
20424
start 20425
20425
start 20426
20426
start 20427
20427
start 20428
20428
start 20429
20429
start 20430
20430
start 20431
20431
start 20432
20432
start 20433
20433
start 20434
20434
start 20435
20435
start 20436
20436
start 20437
20437
start 20438
20438
start 20439
20439
star

20840
start 20841
20841
start 20842
20842
start 20843
20843
start 20844
20844
start 20845
20845
start 20846
20846
start 20847
20847
start 20848
20848
start 20849
20849
start 20850
20850
start 20851
20851
start 20852
20852
start 20853
20853
start 20854
20854
start 20855
20855
start 20856
20856
start 20857
20857
start 20858
20858
start 20859
20859
start 20860
20860
start 20861
20861
start 20862
20862
start 20863
20863
start 20864
20864
start 20865
20865
start 20866
20866
start 20867
20867
start 20868
20868
start 20869
20869
start 20870
20870
start 20871
20871
start 20872
20872
start 20873
20873
start 20874
20874
start 20875
20875
start 20876
20876
start 20877
20877
start 20878
20878
start 20879
20879
start 20880
20880
start 20881
20881
start 20882
20882
start 20883
20883
start 20884
20884
start 20885
20885
start 20886
20886
start 20887
20887
start 20888
20888
start 20889
20889
start 20890
20890
start 20891
20891
start 20892
20892
start 20893
20893
start 20894
20894
start 20895
20895
star

21296
start 21297
21297
start 21298
21298
start 21299
21299
start 21300
21300
start 21301
21301
start 21302
21302
start 21303
21303
start 21304
21304
start 21305
21305
start 21306
21306
start 21307
21307
start 21308
21308
start 21309
21309
start 21310
21310
start 21311
21311
start 21312
21312
start 21313
21313
start 21314
21314
start 21315
21315
start 21316
21316
start 21317
21317
start 21318
21318
start 21319
21319
start 21320
21320
start 21321
21321
start 21322
21322
start 21323
21323
start 21324
21324
start 21325
21325
start 21326
21326
start 21327
21327
start 21328
21328
start 21329
21329
start 21330
21330
start 21331
21331
start 21332
21332
start 21333
21333
start 21334
21334
start 21335
21335
start 21336
21336
start 21337
21337
start 21338
21338
start 21339
21339
start 21340
21340
start 21341
21341
start 21342
21342
start 21343
21343
start 21344
21344
start 21345
21345
start 21346
21346
start 21347
21347
start 21348
21348
start 21349
21349
start 21350
21350
start 21351
21351
star

21752
start 21753
21753
start 21754
21754
start 21755
21755
start 21756
21756
start 21757
21757
start 21758
21758
start 21759
21759
start 21760
21760
start 21761
21761
start 21762
21762
start 21763
21763
start 21764
21764
start 21765
21765
start 21766
21766
start 21767
21767
start 21768
21768
start 21769
21769
start 21770
21770
start 21771
21771
start 21772
21772
start 21773
21773
start 21774
21774
start 21775
21775
start 21776
21776
start 21777
21777
start 21778
21778
start 21779
21779
start 21780
21780
start 21781
21781
start 21782
21782
start 21783
21783
start 21784
21784
start 21785
21785
start 21786
21786
start 21787
21787
start 21788
21788
start 21789
21789
start 21790
21790
start 21791
21791
start 21792
21792
start 21793
21793
start 21794
21794
start 21795
21795
start 21796
21796
start 21797
21797
start 21798
21798
start 21799
21799
start 21800
21800
start 21801
21801
start 21802
21802
start 21803
21803
start 21804
21804
start 21805
21805
start 21806
21806
start 21807
21807
star

In [14]:
preds_npy = np.array(preds)

In [15]:
preds_npy.shape

(21892, 87554)

In [28]:
np.save("test_softdtw.npy",preds_npy)

In [18]:
loaded_preds = np.loadtxt("test_softdtw.npy")

In [19]:
np.allclose(loaded_preds,preds_npy)

True

In [25]:
sorted_preds = np.argsort(preds_npy,axis=1)

In [26]:
sorted_preds

array([[61241, 68745, 10446, ..., 77697, 78449, 75727],
       [67094, 41903, 51790, ..., 77697, 78449, 75727],
       [49152, 18457, 54114, ..., 77697, 78449, 75727],
       ...,
       [81135, 84565, 86156, ..., 77697, 78449, 75727],
       [85430, 82040, 81726, ..., 77697, 78449, 75727],
       [85715, 83502, 82181, ..., 77697, 78449, 75727]])

In [51]:
np.save("test_softdtw_sorted.npy",sorted_preds)

In [40]:
sorted_preds.max()

87553

In [41]:
mit_train_y_complete.shape

(87554,)

In [45]:
from collections import Counter
pred_3nn = []
for i in range(mit_test_y.shape[0]):
    class_counts = Counter()
    for j in range(3):
        class_counts[mit_train_y_complete[sorted_preds[i][j]]] += 1
    most_com = class_counts.most_common()
    pred_3nn.append(most_com[0][0])

In [46]:
from collections import Counter
pred_5nn = []
for i in range(mit_test_y.shape[0]):
    class_counts = Counter()
    for j in range(5):
        class_counts[mit_train_y_complete[sorted_preds[i][j]]] += 1
    most_com = class_counts.most_common()
    pred_5nn.append(most_com[0][0])

In [34]:
class_counts.most_common()[0][0]

0.0

In [36]:
mit_train_y_complete.dtype

dtype('float64')

In [24]:
#1-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
#pred = test_pred_cat.argmax(1)
pred = mit_train_y_complete[np.argmin(preds_npy,axis=1)]
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[17897   120    69    14    18]
 [  193   345    12     6     0]
 [   64     2  1361    16     5]
 [   19     0    18   125     0]
 [   34     2     9     1  1562]]
accuracy: 0.9725013703636032
precision: 0.8804311507609588
recall: 0.8582441765926617
f1: 0.8683396728062899


[[17897   120    69    14    18]
 [  193   345    12     6     0]
 [   64     2  1361    16     5]
 [   19     0    18   125     0]
 [   34     2     9     1  1562]]
accuracy: 0.9725013703636032
precision: 0.8804311507609588
recall: 0.8582441765926617
f1: 0.8683396728062899

In [47]:
#3-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = pred_3nn
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[17959    77    62     8    12]
 [  196   337    16     7     0]
 [   79     2  1340    17    10]
 [   21     0    20   121     0]
 [   46     0    12     1  1549]]
accuracy: 0.9732322309519459
precision: 0.8974514095912767
recall: 0.8465951414888275
f1: 0.8689555727619525


In [50]:
#5-nn
import sklearn.metrics
average_metric = 'macro'
true = mit_test_y
pred = pred_5nn
print(sklearn.metrics.confusion_matrix(y_true=true, y_pred=pred))
print(f"accuracy: {sklearn.metrics.accuracy_score(true, pred)}")
print(f"precision: {sklearn.metrics.precision_score(true, pred, average=average_metric)}")
print(f"recall: {sklearn.metrics.recall_score(true, pred, average=average_metric)}")
print(f"f1: {sklearn.metrics.f1_score(true, pred, average=average_metric)}")


[[17985    59    54     8    12]
 [  205   327    16     8     0]
 [   83     3  1337    17     8]
 [   23     0    21   118     0]
 [   54     0    15     0  1539]]
accuracy: 0.9732322309519459
precision: 0.9031792204442866
recall: 0.837923177143514
f1: 0.8658476913494869
